### ISSUE TITLE
Add `first(orCreate:)` convenience method to `QueryBuilder`

### ISSUE THREAD

**Issue by mattpolzin** [vapor/fluent-kit#103]
This is (kind of) similar to what is accomplished by upsert, as described in [this issue](https://github.com/vapor/fluent-kit/issues/50), but it would be useful to also be able to say "I want to create this record unless it already exists, in which case give me the existing record (there is no updating in this case)." This will be familiar to anyone who has used the Rails ActiveRecord `find_or_create_by` before.

In some ways it would be ideal to hang this off of a model and let unique constraints take care of the "does this record exist?" question. Nevertheless, I think a very useful implementation could just hang off of `QueryBuilder` and take advantage of any filters the user has applied.

I'm imagining the following function signature:
```swift
extension QueryBuilder {
  public func first(orCreate newModel: @escaping @autoclosure () -> Model) -> EventLoopFuture<Model>
}
```

which would look something like this at the call site:
```swift
User.query(on: database)
  .filter(\.$name == "Joe")
  .first(orCreate: User(name: "Joe"))
```

The implementation is easy to imagine because fluent kit already provides the building blocks.

**Comment by tanner0101** [comment]
+1 this seems like a nice, model-centric way to look at upsert that fits well with the existing API.

**Comment by mattpolzin** [comment]
WIP https://github.com/mattpolzin/fluent-kit/blob/feature/103/first-or-create/Sources/FluentKit/Query/QueryBuilder.swift#L610..L625

**Comment by mattpolzin** [comment]
https://github.com/vapor/fluent-kit/pull/107 implemented this non-atomically. We are going to leave the issue open and re-implement atomically as with upsert.

**Comment by tanner0101** [comment]
Closing in favor of #50. The syntax proposed here is good though 👍
