### ISSUE TITLE
Add batch delete on array of models

### ISSUE THREAD

**Issue by davuthdv** [vapor/fluent-kit#114]
### Request
Currently, there's a method `.create(on database: Database)` on an array of models. There should be a similar method for delete.

### Environment
- Vapor Framework version: 4.0.0-beta-3
- fluent-kit: 1.0.0-beta.2.4

**Comment by tanner0101** [comment]
This will be available in the next release, thanks!

**Comment by Flatout73** [comment]
What about `update` as well? :)

**Comment by 0xTim** [comment]
@Flatout73 do you mean when you have an array of models you want to update, all with their new values, or you want to perform a query like `UPDATE MyTable SET something=1 WHERE...`?

**Comment by Flatout73** [comment]
@0xTim Yep, array of models for batch update, like this for deletion:
<img width="702" alt="Снимок экрана 2020-12-11 в 04 18 03" src="https://user-images.githubusercontent.com/17963739/101849058-f3082680-3b67-11eb-9790-0c5b25d98276.png">

**Comment by 0xTim** [comment]
@Flatout73 so the reason why that's not implemented is because it doesn't offer much for updates. With an update you could write
```swift
let myModelsToUpdate: [MyModel] = getModelsToUpdate()
return myModelsToUpdate.map { $0.update(on: req.db) }.flatten(on: req.eventLoop) 
```
That will make N queries to the DB (where N is the size of the array).

The delete and create helpers for collection that you linked above convert the operations into a single query

**Comment by Flatout73** [comment]
@0xTim ok, thank you. However, I use Vapor for telegram bot (via https://github.com/givip/Telegrammer) and don't have direct access to request. How can I get eventLoop? is `self.app.eventLoopGroup.next()` good practice?

**Comment by 0xTim** [comment]
@Flatout73 yep that's the right way for an `Application`
