### ISSUE TITLE
Add feature to inject eager loaded values

### ISSUE THREAD

**Issue by davuthdv** [vapor/fluent-kit#116]
### Steps to reproduce
- Create a record -> category
- Create children records of the category -> products
- Injecting products into the category object created earlier

### Expected behavior
`category.products` should contain data.

### Actual behavior
fatal error "Use $ prefix to access"

### Benefits
1. No need do the query again on the category (by including the products this time)
2. As including grandchildren (or even grand grandchildren) is not supported (yet), there are cases where it's useful to do the query on grandchildren and attach manually. Doing so, we can still re-use the original models without having to create separate identical objects that do not conform to models just to store the data.

### Environment
- Vapor Framework version: 4.0.0-beta-3
- fluent-kit: 1.0.0-beta.2.4

**Comment by tanner0101** [comment]
This is now possible by using the settable `value` property on relations, e.g.:

```swift
planet.$star.value = Star(...)
```
