### ISSUE TITLE
.with(_ field: KeyPath): error when the id is not found

### ISSUE THREAD

**Issue by davuthdv** [vapor/fluent-kit#117]
### Query
```swift
Category.query(on: db)
    .filter(\.$id == id)
    .with(\.$translations) // children
    .first()
```

### Steps to reproduce
- Running query above with id already existed in db -> it works
- Running the same query above with id that doesn't exist

### Expected behavior
It should still works

### Actual behavior
It crashes with error `error: syntax error at or near ")" (scanner_yyerror)`
It's the issue with `.with(field)`

### Environment
- Vapor Framework version: 4.0.0-beta-3
- fluent-kit: 1.0.0-beta.2.4

**Comment by RamblinWreck77** [comment]
+1, ran into this exact thing when eager loading.

**Comment by jordanebelanger** [comment]
+1 having that issue as well on mysql
