### ISSUE TITLE
Nested calls to `transaction(on:)` should not start new transactions

### ISSUE THREAD

**Issue by mxcl** [vapor/fluent-kit#119]
In Vapor 3 this causes the inner call to close the transaction (at least for Postgres) since the second request to start a transaction does not fail the transaction (it outputs a warning).

It seems correct that Vapor would count the number of calls to this function per connection because eg. a helper function may want some work it does to be transactional, and the caller of the helper code may already have started a transaction.

This ticket created as requested by @tanner0101 so it can be implemented for Vapor 4.

Might make #23 less necessary.

**Comment by tanner0101** [comment]
Fixed in #192
