### ISSUE TITLE
Auto-generated foreign key names can be too long

### ISSUE THREAD

**Issue by jordanebelanger** [vapor/fluent-kit#121]
The maximum length of MySQL's foreign key's identifiers is 64 character. That limit is regularly broken by the automatically generated fk name of fluent-kit.

This problem could be alleviated somewhat by allowing users to specify custom FK name as mentioned in https://github.com/vapor/fluent-kit/issues/118

There should be a mecanism that limits the length of foreign key's identifiers so that this problem is avoided.

**Comment by jordanebelanger** [comment]
Reference to our Disc talk about the issue.
![image](https://user-images.githubusercontent.com/1856085/71284784-8e8a0100-2331-11ea-80d9-cc26b5151d8b.png)

**Comment by mcdappdev** [comment]
@tanner0101 is this still planned for the final release?

**Comment by tanner0101** [comment]
This was fixed in https://github.com/vapor/sql-kit/pull/102
