### ISSUE TITLE
Invalid @ID assertion

### ISSUE THREAD

**Issue by grosch** [vapor/fluent-kit#122]
I have these definitions, and when I run I'm getting this error:

> fatal error: id property must be declared using @ID: file ...FluentKit/Model/Model.swift, line 225
2019-12-23 13:32:35.441831-0800 Run[65971:1219033] Fatal error: id property must be declared using @ID: file .../FluentKit/Model/Model.swift, line 225

```swift
public protocol PassKitPass: Model {
    var id: UUID? { get set }
    
    ...
}

internal extension PassKitPass {
    var _$id: ID<UUID> {
        guard let mirror = Mirror(reflecting: self).descendant("_id"),
            let id = mirror as? ID<UUID> else {
                fatalError("id property must be declared using @ID")
        }
        
        return id
    }
    
   ...
}

open class PKPass: PassKitPass {
    public static let schema = "passes"

    @ID(key: "id")
    public var id: UUID?
    
    ...
}
```

Those items are all defined in the PassKit module I'm writing, and then in my actual project I made the concrete Pass class like so:

```swift
public class Pass: PKPass {
    @Field(key: "punches")
    var punches: Int
}
```

So, as you can see, the ID is definitely there with an @ID property.  Why am I getting an assertion?

**Comment by calebkleveter** [comment]
The issue is almost certainly that you are using sub-classing. Fluent (and Vapor in general) is designed around the protocol-oriented paradigm, rather than object-oriented.

The error should be resolved if you move the `id` declaration to the `Pass` model.

**Comment by grosch** [comment]
Is there a way to let it work with subclassing?  I don't want to have to tell everyone to duplicate a big chunk of code when I can just give them most of it already.

**Comment by calebkleveter** [comment]
Not currently, no. Besides, if you are duplicating large chunks of code for multiple different models, you might want to redesign your database structure.

**Comment by grosch** [comment]
Well, the intent here is that all passes same the same base set of fields, and so I can just give them something to inherit from that has all the "required" stuff, and then they add their extras.

**Comment by grosch** [comment]
I suppose I could give them the `PKPass` and then tell them to create a separate table that holds the data for the pass itself.  It's just not as "clean" of an API that way.
