### ISSUE TITLE
Fetch siblings with pivot

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent-kit#14]
The siblings relation requires a pivot table to relate models. In this table, the user can store some extra information regarding the relation. However, it's currently not easy to access that pivot info when you fetch siblings. Fluent 4 should make this easier.

**Comment by patchthecode** [comment]
I was just wondering if this was completed or still pending?

**Comment by patchthecode** [comment]
even if you do not have the update ready, is it possibly you can guide me to a solution so i can hack up something myself?
