### ISSUE TITLE
Unknown binary operator ~~

### ISSUE THREAD

**Issue by cit117** [vapor/fluent-kit#144]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/54506518/73810055-34c19580-4810-11ea-8336-95de7deac06f.png">

**Comment by proggeramlug** [comment]
Short-term fix: 
```import FluentKit```

@tanner0101 knows though (he and I had that issue just a moment ago) and is working on a fix

**Comment by tanner0101** [comment]
Swift's `@_exported` feature is not respecting these operators for some reason. This was also an issue in Fluent 3. I'm looking into a fix. As @proggeramlug says, `import FluentKit` should work for the time being.

**Comment by tanner0101** [comment]
This has been fixed with a workaround. For reference, here's the SR: https://bugs.swift.org/browse/SR-12132
