### ISSUE TITLE
DatabaseQuery w/ raw sql value support

### ISSUE THREAD

**Issue by tunjifw** [vapor/fluent-kit#152]
Feature Request:

It'd be nice to use a raw sql value type when using filter on a database query..

`filter(\.$timestamp > .sql(raw: ...))`

**Comment by tanner0101** [comment]
Thanks for the issue @tunjifw. I did a quick test and it looks like this can work. 

```swift
let moon = try Moon.query(on: self.database)
    .filter(\.$name == .sql(raw: "'Moon'"))
    .first().wait()

XCTAssertNotNil(moon)
XCTAssertEqual(moon?.name, "Moon")
```

I'll work on adding the rest of the operators.

**Comment by tanner0101** [comment]
This was added in #159
