### ISSUE TITLE
Parent eagerLoad fatalError when parent has been soft-deleted

### ISSUE THREAD

**Issue by namolnad** [vapor/fluent-kit#158]
@tanner0101 I did figure out my issue which i was trying to debug with #157. I have a `UserConnections` table which has `Parent` fields `follower` and `followee`. I had a query looking up all the followers and followees for a given user, and was eager loading the corresponding users, but some of the users whose IDs were present in the connections table had been soft deleted. As such, they were not returned from the underlying eagerLoad query and when the eagerLoad was accessed there was no data present, causing the fatalError.

I'm honestly not sure what the best behavior for this scenario (as those connections probably should be deleted/soft deleted as well), but if nothing else, it seems the messaging could be improved to indicate that the eager load was not fulfilled due to a soft deletion. This error message made it a bit difficult to understand what was happening: `Fatal error: Parent relation not eager loaded, use $ prefix to access: file /build/.build/checkouts/fluent-kit/Sources/FluentKit/Properties/Parent.swift, line 11`

Would love to hear your thoughts. Thanks!

**Comment by tanner0101** [comment]
@namolnad you can check if a relation has been eager loaded by using `value`:

```swift
if let star = planet.$star.value {
    print(star.name) // String
} else {
    // not eager loaded
}
```

However, if this is a parent relation, it seems to me that the child model should also be getting soft-deleted when the parent is.
