### ISSUE TITLE
Support delete with NOT EXISTS

### ISSUE THREAD

**Issue by grosch** [vapor/fluent-kit#166]
I need to be able to model this, in Fluent.

```sql
DELETE FROM devices d
WHERE NOT EXISTS (
	SELECT 1
	FROM registrations r
	WHERE d."id" = r.device_id
	LIMIT 1
);
```

That's the PostgreSQL version of  "Delete all rows from the devices table where the device ID doesn't appear in the registrations table under the 'device_id' foreign key"

**Comment by tanner0101** [comment]
Could you provide examples of other ORMs that support this feature in their model or query builder APIs? If so we can re-open. 

Otherwise, raw SQL commands are a prefectly good solution to this problem 👍
