### ISSUE TITLE
compile error with swift-toolchain-5.1.

### ISSUE THREAD

**Issue by imkerberos** [vapor/fluent-kit#168]
as title

`
Fetching https://github.com/vapor/postgres-kit.git
Fetching https://github.com/apple/swift-nio-http2.git
Fetching https://github.com/swift-server/async-http-client.git
Fetching https://github.com/apple/swift-log.git
Fetching https://github.com/vapor/async-kit.git
Fetching https://github.com/vapor/console-kit.git
Fetching https://github.com/apple/swift-nio-ssl.git
Fetching https://github.com/apple/swift-metrics.git
Fetching https://github.com/vapor/websocket-kit.git
Fetching https://github.com/vapor/fluent-kit.git
Fetching https://github.com/vapor/multipart-kit.git
Fetching https://github.com/vapor/vapor.git
Fetching https://github.com/vapor/open-crypto.git
Fetching https://github.com/vapor/postgres-nio.git
Fetching https://github.com/vapor/sql-kit.git
Fetching https://github.com/apple/swift-nio.git
Fetching https://github.com/vapor/fluent-postgres-driver.git
Fetching https://github.com/vapor/routing-kit.git
Fetching https://github.com/ianpartridge/swift-backtrace.git
Fetching https://github.com/apple/swift-nio-extras.git
Fetching https://github.com/vapor/fluent.git
Completed resolution in 183.06s
Cloning https://github.com/vapor/multipart-kit.git
Resolving https://github.com/vapor/multipart-kit.git at 4.0.0-beta.2
Cloning https://github.com/vapor/vapor.git
Resolving https://github.com/vapor/vapor.git at 4.0.0-beta.3.21
Cloning https://github.com/vapor/async-kit.git
Resolving https://github.com/vapor/async-kit.git at 1.0.0-beta.2.3
Cloning https://github.com/apple/swift-log.git
Resolving https://github.com/apple/swift-log.git at 1.2.0
Cloning https://github.com/apple/swift-nio-http2.git
Resolving https://github.com/apple/swift-nio-http2.git at 1.9.1
Cloning https://github.com/vapor/fluent.git
Resolving https://github.com/vapor/fluent.git at 4.0.0-beta.2.4
Cloning https://github.com/swift-server/async-http-client.git
Resolving https://github.com/swift-server/async-http-client.git at 1.1.0
Cloning https://github.com/vapor/fluent-postgres-driver.git
Resolving https://github.com/vapor/fluent-postgres-driver.git at 2.0.0-beta.3
Cloning https://github.com/vapor/routing-kit.git
Resolving https://github.com/vapor/routing-kit.git at 4.0.0-beta.3
Cloning https://github.com/apple/swift-nio-ssl.git
Resolving https://github.com/apple/swift-nio-ssl.git at 2.6.2
Cloning https://github.com/vapor/console-kit.git
Resolving https://github.com/vapor/console-kit.git at 4.0.0-beta.2.1
Cloning https://github.com/apple/swift-metrics.git
Resolving https://github.com/apple/swift-metrics.git at 1.2.1
Cloning https://github.com/vapor/websocket-kit.git
Resolving https://github.com/vapor/websocket-kit.git at 2.0.0-beta.2.3
Cloning https://github.com/vapor/sql-kit.git
Resolving https://github.com/vapor/sql-kit.git at 3.0.0-beta.6.5
Cloning https://github.com/vapor/open-crypto.git
Resolving https://github.com/vapor/open-crypto.git at 4.0.0-beta.2
Cloning https://github.com/apple/swift-nio.git
Resolving https://github.com/apple/swift-nio.git at 2.14.0
Cloning https://github.com/vapor/fluent-kit.git
Resolving https://github.com/vapor/fluent-kit.git at 1.0.0-beta.4
Cloning https://github.com/apple/swift-nio-extras.git
Resolving https://github.com/apple/swift-nio-extras.git at 1.4.0
Cloning https://github.com/ianpartridge/swift-backtrace.git
Resolving https://github.com/ianpartridge/swift-backtrace.git at 1.1.1
Cloning https://github.com/vapor/postgres-kit.git
Resolving https://github.com/vapor/postgres-kit.git at 2.0.0-beta.3.6
Cloning https://github.com/vapor/postgres-nio.git
Resolving https://github.com/vapor/postgres-nio.git at 1.0.0-beta.2.9
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:11:5: error: unknown attribute 'ID'
    @ID(key: "id")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:14:5: error: unknown attribute 'Field'
    @Field(key: "name")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:17:5: error: unknown attribute 'Field'
    @Field(key: "batch")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:20:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "created_at", on: .create)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:23:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "updated_at", on: .update)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:129:67: error: contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored
        item.migration.revert(on: self.database(item.id)).flatMap {
                                                                  ^
                                                                   _ in
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:141:57: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).sort(\.$batch, .descending).first().map { log in
                                                        ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:160:59: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).filter(\.$batch == batch).all().map { logs in
                                                          ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:11:5: error: unknown attribute 'ID'
    @ID(key: "id")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:14:5: error: unknown attribute 'Field'
    @Field(key: "name")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:17:5: error: unknown attribute 'Field'
    @Field(key: "batch")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:20:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "created_at", on: .create)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:23:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "updated_at", on: .update)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:129:67: error: contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored
        item.migration.revert(on: self.database(item.id)).flatMap {
                                                                  ^
                                                                   _ in
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:141:57: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).sort(\.$batch, .descending).first().map { log in
                                                        ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:160:59: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).filter(\.$batch == batch).all().map { logs in
                                                          ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:11:5: error: unknown attribute 'ID'
    @ID(key: "id")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:14:5: error: unknown attribute 'Field'
    @Field(key: "name")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:17:5: error: unknown attribute 'Field'
    @Field(key: "batch")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:20:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "created_at", on: .create)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:23:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "updated_at", on: .update)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:129:67: error: contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored
        item.migration.revert(on: self.database(item.id)).flatMap {
                                                                  ^
                                                                   _ in
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:141:57: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).sort(\.$batch, .descending).first().map { log in
                                                        ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:160:59: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).filter(\.$batch == batch).all().map { logs in
                                                          ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:11:5: error: unknown attribute 'ID'
    @ID(key: "id")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:14:5: error: unknown attribute 'Field'
    @Field(key: "name")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:17:5: error: unknown attribute 'Field'
    @Field(key: "batch")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:20:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "created_at", on: .create)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:23:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "updated_at", on: .update)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:129:67: error: contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored
        item.migration.revert(on: self.database(item.id)).flatMap {
                                                                  ^
                                                                   _ in
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:141:57: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).sort(\.$batch, .descending).first().map { log in
                                                        ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:160:59: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).filter(\.$batch == batch).all().map { logs in
                                                          ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:11:5: error: unknown attribute 'ID'
    @ID(key: "id")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:14:5: error: unknown attribute 'Field'
    @Field(key: "name")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:17:5: error: unknown attribute 'Field'
    @Field(key: "batch")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:20:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "created_at", on: .create)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:23:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "updated_at", on: .update)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:129:67: error: contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored
        item.migration.revert(on: self.database(item.id)).flatMap {
                                                                  ^
                                                                   _ in
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:141:57: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).sort(\.$batch, .descending).first().map { log in
                                                        ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:160:59: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).filter(\.$batch == batch).all().map { logs in
                                                          ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:11:5: error: unknown attribute 'ID'
    @ID(key: "id")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:14:5: error: unknown attribute 'Field'
    @Field(key: "name")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:17:5: error: unknown attribute 'Field'
    @Field(key: "batch")
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:20:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "created_at", on: .create)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/MigrationLog.swift:23:5: error: unknown attribute 'Timestamp'
    @Timestamp(key: "updated_at", on: .update)
    ^
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:129:67: error: contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored
        item.migration.revert(on: self.database(item.id)).flatMap {
                                                                  ^
                                                                   _ in
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:141:57: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).sort(\.$batch, .descending).first().map { log in
                                                        ^~~~~~~~
/Users/kerberos/ws/playground/swift/Vapor4/.build/checkouts/fluent-kit/Sources/FluentKit/Migration/Migrator.swift:160:59: error: type of expression is ambiguous without more context
        MigrationLog.query(on: self.database(nil)).filter(\.$batch == batch).all().map { logs in
                                                          ^~~~~~~~
[763/782] Merging module NIOHTTP1

`

**Comment by 0xTim** [comment]
The latest Fluent betas now require 5.2 as per [this forum post](https://forums.swift.org/t/vapor-4-fluent-now-requires-swift-5-2/33849)
