### ISSUE TITLE
`.field()` on `QueryBuilder` needs to let me name the column

### ISSUE THREAD

**Issue by grosch** [vapor/fluent-kit#199]
In the below, you're auto-generating names for the columns.  *Today* they are stations_name, stations_client_id, and clients_name.  Tomorrow, who knows what Vapor will decide is a good naming convention to use.  There should be an optional second parameter to `.field()` that lets us specify the "AS" name that you generate on the SQL call.

That also lets me avoid using `CodingKeys` on the struct that I'll decode this into.

```swift
return Station.query(on: req.db)
    .join(Client.self, on: \Station.$client.$id == \Client.$id)
    .field(\.$name)
    .field(\.$client.$id)
    .field(Client.self, \.$name)
    .sort(\.$name)
    .all()
```

**Comment by tanner0101** [comment]
IMO Fluent _should_ control the actual name of a key and keep that opaque to the user. This is critical to getting things like joining and eager loading to work correctly. 

What was the reasoning behind wanting this change again? We should be able to find an alternate solution.
