### ISSUE TITLE
Unnecessary deleted time check

### ISSUE THREAD

**Issue by grosch** [vapor/fluent-kit#204]
You're generating SQL like so

```sql
SELECT "stations"."name" AS "stations_name", "stations"."client_id" AS "stations_client_id", "clients"."name" AS "clients_name" 
FROM "stations" 
INNER JOIN "clients" ON "stations"."client_id" = "clients"."id" 
WHERE ("stations"."deleted" IS NULL OR "stations"."deleted" > $1) AND ("clients"."deleted" IS NULL OR "clients"."deleted" > $2) 
ORDER BY "stations"."name" ASC
```

I believe the "OR" parts of the two where clauses are not necessary.  The time passed in is the time of the query, meaning it's not going to be possible for anything to have a deleted date after that.  Just checking the two `IS NULL` items should be enough.

What was the reasoning for adding the time check?

**Comment by tanner0101** [comment]
Items can have their deleted at date set in the future. This is useful for having things expire after a set amount of time.
