### ISSUE TITLE
Provide mechanism to assert if we are inside a transaction

### ISSUE THREAD

**Issue by mxcl** [vapor/fluent-kit#23]
Much like libdispatch provides:

    dispatchPrecondition(.onQueue(myQueue))

I would like a way to assert that my code is inside a transaction in some situations, could be:

    fluentPrecondition(.inTransaction)
    fluentPrecondition(.notInTransaction)

I am happy to provide the PR, if directed to a way to detect these conditions. If it is possible that is.

**Comment by tanner0101** [comment]
Fixed by #192
