### ISSUE TITLE
unique(on:) failing when update filed constraint.

### ISSUE THREAD

**Issue by tuchangwei** [vapor/fluent-kit#235]
I want to make the category name unique, but the migration is failed.
```swift
struct ModifyNameToCategory: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        return database.schema(ArticleCategory.schema)
            .unique(on: ArticleCategory.nameKey)
            .update()
    }
    func revert(on database: Database) -> EventLoopFuture<Void> {
        return database.schema(ArticleCategory.schema)
            .delete()
    }
}
```
error:
```swift
[ INFO ] query read _fluent_migrations
[ INFO ] query read _fluent_migrations limits=[count(1)]
[ ERROR ] syntax error at end of input (scanner_yyerror)
[ ERROR ] server: syntax error at end of input (scanner_yyerror)
Fatal error: Error raised at top level: server: syntax error at end of input (scanner_yyerror): file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.8.25.8/swift/stdlib/public/core/ErrorType.swift, line 200
```

**Comment by tuchangwei** [comment]
Hello @tanner0101 , I have found where the issue is, when we `update`, we didn't handle the `constraint` like `create` did.

https://github.com/vapor/fluent-kit/blob/0e855b630c2ef005465d904d1de2263cdbeca990/Sources/FluentSQL/SQLSchemaConverter.swift#L24

https://github.com/vapor/fluent-kit/blob/0e855b630c2ef005465d904d1de2263cdbeca990/Sources/FluentSQL/SQLSchemaConverter.swift#L40

**Comment by tuchangwei** [comment]
Hello @tanner0101 , I have found where is the issue, when we `update`, we didn't handle the `constraint` like `create` did.

https://github.com/vapor/fluent-kit/blob/0e855b630c2ef005465d904d1de2263cdbeca990/Sources/FluentSQL/SQLSchemaConverter.swift#L24

https://github.com/vapor/fluent-kit/blob/0e855b630c2ef005465d904d1de2263cdbeca990/Sources/FluentSQL/SQLSchemaConverter.swift#L40

**Comment by tanner0101** [comment]
Support for adding constraints to existing tables needs to be added and tested. I'll make sure to include this before the official release, thanks.
