### ISSUE TITLE
Improper en/decoding of bools and dates in MySQL

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent-kit#254]
Filtering on boolean columns with bool primitives doesn't work. 

```swift
po Term.query(on: conn).filter(\.$district.$id == 3).all().wait()
```

Returns:

```
Term(output: ["terms_deletedAt": nil, "terms_createdAt": 2020-04-21 00:50:55 +0000, "terms_isCurrent": true, "terms_name": "Spring 2020", "terms_id": 4, "terms_updatedAt": 2020-04-21 00:50:55 +0000, "terms_district_id": 3])
```

(Notice `isCurrent`) is true. But if I do:

```swift
po Term.query(on: conn).filter(\.$district.$id == 3).filter(\.$isCurrent == true).all().wait()
```

I get 0 results. However, this does work:

```swift
po Term.query(on: conn).filter(\.$district.$id == 3).filter(\.$isCurrent == .custom("1")).all().wait()
```

**Comment by mcdappdev** [comment]
It appears that this has something to do with a crash that's occurring in `MySQLDataDecoder` with both booleans and dates for me. Here's an example of the crash with a bool:

<img width="1451" alt="Screen Shot 2020-04-20 at 9 13 58 PM" src="https://user-images.githubusercontent.com/11842593/79817810-e53d3100-834b-11ea-8bb3-be3f103bf573.png">
<img width="294" alt="Screen Shot 2020-04-20 at 9 14 03 PM" src="https://user-images.githubusercontent.com/11842593/79817821-e8d0b800-834b-11ea-9b4f-cf179f019b4e.png">


```
po data
▿ "\u{01}"
  ▿ type : MYSQL_TYPE_VAR_STRING
    - rawValue : 253
  - format : MySQLNIO.MySQLData.Format.binary
  ▿ buffer : Optional<ByteBuffer>
    ▿ some : ByteBuffer { readerIndex: 0, writerIndex: 1, readableBytes: 1, capacity: 1, slice: _ByteBufferSlice { 26..<27 }, storage: 0x0000000103879000 (32768 bytes) }
      ▿ _storage : <_Storage: 0x100d677e0>
      - _readerIndex : 0
      - _writerIndex : 1
      ▿ _slice : _ByteBufferSlice { 26..<27 }
        - upperBound : 27
        ▿ _begin : 26
          - b12 : 26
          - b3 : 0
  - isUnsigned : false
```

This happens after trying to pull in a model that has a bool value saved, i.e. `Model.query(on: conn).all()`

**Comment by 0xTim** [comment]
I've just hit this as well, it seems to only return rows where the column is false. The query in the logs looks right:
```
2020-04-21T14:46:28+0100 debug: database-id=mysql SELECT COUNT(`BlogPost`.`postID`) AS `aggregate` FROM `BlogPost` WHERE `BlogPost`.`author` = ? AND `BlogPost`.`published` = ? [1, true]
```
But it returns only the `BlogPost`s where `published` is false

**Comment by tanner0101** [comment]
This was fixed in https://github.com/vapor/fluent-mysql-driver/pull/168
