### ISSUE TITLE
Empty array on RHS of `IN` query serializes incorrect SQL 

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent-kit#257]
I think this is my last Fluent bug before I'm done migrating, I promise :) 

This Swift code:

```swift
User.query(on: req.db).filter(\User.$id ~~ [1]).filter(\User.$id !~ []).all()
```

Results in the following SQL:

```sql
SELECT
	`users`.`id` AS `users_id`,
        ...
FROM
	`users`
WHERE
	`users`.`id` IN (1)
	AND 1 = 0
```

Notice the `AND 1 = 0` statement. The same happens if you reverse it - empty array for `~~` and non-empty for `!~`

**Comment by tanner0101** [comment]
`1 = 0 ` is correct for `id ~~ []` since it's not possible for the ID to be in the empty set. However, for `id !~ []` we should have `1 = 1` since it's always true that the id will not be in the empty set.
