### ISSUE TITLE
Support of multiple inserts

### ISSUE THREAD

**Issue by jonny7** [vapor/fluent-kit#259]
Hi Tanner

If this is already included please close. I'm wondering about the inclusion of support for fluent for multiple inserts. For example in Postgres it would be

```sql
INSERT INTO public."Item" ("Id", name)
VALUES  ('1', 'name1'),
        ('2', 'name2'),
        ('3','name3')
```

Oracle also has a multiple insert, although I don't think it's a supported DB.

```sql
INSERT ALL
  INTO mytable (column1, column2, column_n) VALUES (expr1, expr2, expr_n)
  INTO mytable (column1, column2, column_n) VALUES (expr1, expr2, expr_n)
  INTO mytable (column1, column2, column_n) VALUES (expr1, expr2, expr_n)
SELECT * FROM dual;
```

MySQL does support this, but it's a bit more complex with a CTE. This would be far more efficient than looping over a data set and doing many single inserts. I've put this ticket in Postgres-Kit as it's the more easily supported functionality

**Comment by tanner0101** [comment]
FluentKit supports multiple inserts via an extension on an array of models:

```swift
models.create(on: db)
```
