### ISSUE TITLE
Add `Model` append to `TestOutput` creation for `TestDatabase` use.

### ISSUE THREAD

**Issue by mattpolzin** [vapor/fluent-kit#264]
Note this is an `XCTFluent` issue.

It would be nice if there was a shortcut for appending `Model`s to the output of a `TestDatabase`. Passing in dictionaries is great for testing that models decode as expected, but passing `Model`s in can make it much easier to test controller logic while still not relying on an actual Database instance.

**Comment by tanner0101** [comment]
#265 was merged, thanks matt
