### ISSUE TITLE
Generate column name from model's KeyPath

### ISSUE THREAD

**Issue by rabc** [vapor/fluent-kit#269]
I am converting a library[1] for using PostGIS with Fluent made from Vapor 3 to 4 and using an extension of `QueryBuilder` to append the filters using PostGIS functions[2].

One of the parameters of the filter functions is a `KeyPath<Model, FieldProtocol>` and I need to convert it to a `String` to create a `SQLColumn` to use as an argument of `SQLFunction`. It is the same that is being done in `SQLQueryConverter`, but this struct has two functions (`path(_:)` and `key(_:)`) to generate the string version of the KeyPath.

These two functions are marked as `private`. There is another way to generate the column name? Otherwise, it would be good to have a public function for it to be used by libraries.

[1] https://github.com/rabc/fluent-postgis/tree/vapor_4
[2] https://github.com/rabc/fluent-postgis/blob/vapor_4/Sources/FluentPostGIS/Queries/QuerySupporting%2BGeometry.swift#L28

**Comment by tanner0101** [comment]
@rabc you can use `Model.path(for: ...)` to get the `[FieldKey]` path to a given property. 

```swift
final class User: Model {
    @Field(key: "first_name")
    var firstName: String
}
User.path(for: \.$firstName) // ["first_name"]
```

The reason this returns an array is because paths can be nested in `@Group`. For example:

```swift
Moon.path(for: \.$planet.$star.$galaxy.$name)
```

Fluent doesn't make use of this yet but it may in the future.

**Comment by rabc** [comment]
Hi @tanner0101 

Yes, I'm using it [here](https://github.com/rabc/fluent-postgis/blob/vapor_4/Sources/FluentPostGIS/Queries/QuerySupporting%2BGeometry.swift#L22), but what I need is a way to create `SQLColumn` or `SQLExpression` from this `[FieldKey]` then use it to create a [custom function](https://github.com/rabc/fluent-postgis/blob/vapor_4/Sources/FluentPostGIS/Queries/QuerySupporting%2BGeometry.swift#L28)

**Comment by tanner0101** [comment]
Something like this should work:

```swift
let name = User.path(for: \.$firstName).map(\.description).joined(separator: "_")
let column = SQLColumn(name)
```
