### ISSUE TITLE
Array.create() attempts to unwrap nil

### ISSUE THREAD

**Issue by JetForMe** [vapor/fluent-kit#272]
Fluent 4

If you attempt to create an array of `Model` objects, and later objects have nil values for some columns, `SQLQueryConverter.fetch(path:from:)` fails because it attempts to extract a non-nil value from the value dictionary.

You can reproduce this with a simple entity containing an optional field. Instantiate two entities, one with the field not nil, the other with it nil. Then try to create them:

```swift
let e1 = MyEntity(field: "foo")
let e2 = MyEntity(field: nil)
try [e1, e2].create(on: self.app.db).wait()  //  Crash
try [e1].create(on: self.app.db).wait()      //  OK
try [e2].create(on: self.app.db).wait()      //  OK
```

**Comment by JetForMe** [comment]
Hey, thanks for looking at this! Forgive me, but I only see a test added for this case, I don't see an actual fix?

**Comment by tanner0101** [comment]
The code around `SQLQueryConverter.fetch(path:from:)` had been refactored previously on the `gm` branch which I'm guessing fixed the bug.
