### ISSUE TITLE
Using a join breaks the use of `.field`

### ISSUE THREAD

**Issue by grosch** [vapor/fluent-kit#274]
Fluent can't query specific fields when using a join.  This will fail

```swift
        return WorkCompleted.query(on: req.db)
            .join(Order.self, on: \WorkCompleted.$order.$id == \Order.$id)
            .with(\.$order)
            .filter(Order.self, \.$month == date)
            .field(\.$amount)
            .field(Order.self, \.$id)
            .field(Order.self, \.$name)
            .all()
            .map { $0.map { Foo(name: $0.order.name, amount: $0.amount) }}
```

It's trying to query "orders_id" instead of "order_id".  If I fully remove the `.field()` specifiers it runs fine.  If it's there, then it fails.

**Comment by tdotclare** [comment]
Unless I'm missing something, this is in fact possible;
```swift
Model.query(on: db).field(\$.fieldname).all()
```
will only return the specific `fieldname` requested.

**Comment by grosch** [comment]
This doesn't work if you use a join.

**Comment by gwynne** [comment]
Marking as a bug - adding a simple join to a query should not obviate the ability to be specific about which data to load. This kind of usage has broad implications ranging from efficiency to security (for example, why load a hashed password into memory if it's not going to be accessed). Fluent should at _least_ be able to manage making the requested keypaths via `.field(_:_:)` match the ones expected by an eager-load join using `.with(_:)`. It should also ensure the appropriate `id` fields are included even if not separately requested.

**Comment by tanner0101** [comment]
I've added a test for this an I'm unable to repro any problems using strictly join and partial selects:

This code:

```swift
let planets = try Planet.query(on: self.database)
    .field(\.$name)
    .join(Star.self, on: \Planet.$star.$id == \Star.$id)
    .field(Star.self, \.$name)
    .all().wait()
```
Is yielding this query:
```sql
SELECT 
    "planets"."name" AS "planets_name", 
    "stars"."name" AS "stars_name" 
FROM "planets" 
INNER JOIN "stars" ON "planets"."star_id" = "stars"."id"
```

I'm guessing the problem here actually has to do with the eager load. Eager loading uses a subquery to fetch the results and is unrelated to the main query and join happening. Thus `field` has no effect. 

Right now there is no way to modify the eager load subquery. This should be fixed (related to https://github.com/vapor/fluent-kit/issues/227). 

Let me know if that makes sense or if I'm missing something. If this is correct, a new issue for partial select eager loading would be appreciated.

**Comment by grosch** [comment]
Your test didn't include a filter.  If you try and filter, then it'll barf.  This query shouldn't require any type of eager loading.  This is the SQL that my example generated when removing the `.with()` line.

```sql
SELECT "work_completed"."amount" AS "work_completed_amount", "orders"."id" AS "orders_id", "orders"."name" AS "orders_name" 
FROM "work_completed"
INNER JOIN "orders" ON "work_completed"."order_id" = "orders"."id" 
WHERE "orders"."month" = $1 AND ("work_completed"."deleted" IS NULL OR "work_completed"."deleted" > $2) AND ("orders"."deleted" IS NULL OR "orders"."deleted" > $3)
```

**Comment by tanner0101** [comment]
I just added a filter to the test and it still worked fine. See related commit.
