### ISSUE TITLE
Using `.with()` should auto-include the join

### ISSUE THREAD

**Issue by grosch** [vapor/fluent-kit#277]
Since the model specifies what the foreign key is, then instead of having to do this:

```swift
return WorkCompleted.query(on: req.db)
    .join(Order.self, on: \WorkCompleted.$order.$id == \Order.$id)
    .with(\.$order)
```

I should be able to simply drop the `.join()` entirely and have fluent know to add it for me.

**Comment by mcdappdev** [comment]
@grosch what is the generated SQL actually doing? I was under the impression this functioned already. I know that it definitely compiles without the `join` statement.

**Comment by grosch** [comment]
It leaves off the join entirely.

**Comment by mcdappdev** [comment]
But how is it fetching the related item then? Is it doing it in Swift vs the database? Just trying to understand what it’s doing vs. what you want it to do.

**Comment by grosch** [comment]
It doesn't fetch the item, that's the point.  The generated SQL has no `JOIN` statement, so the above is just going to return the work_completed table.  If you then add something like 

```swift
.filter(Order.self, \.$month == date)
```

to the query it'll abort because it adds a "WHERE order.month = x" clause and SQL doesn't know what `order` is.

**Comment by mcdappdev** [comment]
Got it - so I’m guessing that it’s doing 2 queries behind the scenes with an IN operator to fetch the actual attached entities (cause that definitely works) 

In this case I’m thinking there should be an option on the .with() method that allows the user to specify .join or .inMethod (or something similar)

**Comment by tanner0101** [comment]
> I should be able to simply drop the .join() entirely and have fluent know to add it for me.

Hmm I'm not sure what you mean by this. Eager loading uses a separate query to fetch its results. These results are filtered based on primary keys. Adding a `join` to the main query is not required nor does it affect the structure of the separate eager load query. 

That said, it is a common pattern to need to `join` + `with` in Fluent. This is somewhat cumbersome. Perhaps we should consider new API for more easily filtering a query by related entities? This is related to #227. 

Let me know if I misunderstood anything. Closing this issue as is.

**Comment by gobuki** [comment]
>  Eager loading uses a separate query to fetch its results. 

Would it be possible at some point to eager load off of the results of a join, rather than a second query with the `IN` operator?  For a very large, nested query using `.with(..)`, I run into :

> Uncaught error: NIOPostgres error: protocol error: Bind count must be <= 32767.

Most internet services probably won't ever need such a large query, but I think it's helpful at times during testing and development. 

I believe Sqlalchemy's `subqueryload` uses a join? I've never run into the bind limit there

**Comment by tanner0101** [comment]
> Would it be possible at some point to eager load off of the results of a join, rather than a second query with the IN operator?

Yes I think that would make sense to add. I had join-based eager loading in some early version of Fluent 4 but removed it due to time constraints. 

I've created an issue for this here https://github.com/vapor/fluent-kit/issues/348
