### ISSUE TITLE
Use of unresolved identifier XCTUnwrap

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/fluent-kit#278]
When generating a project using `swift package generate-xcodeproj` and one of the targets has a dependency on `FluentBenchmark`. Such target doesn't compile. This supposedly works when using `open Package.swift`.

Note: in some cases using `open Package.swift` is not possible. In my specific case I am stuck in a limbo because of https://github.com/mongodb/mongo-swift-driver/issues/387 / https://bugs.swift.org/browse/SR-12009 that require the use of `swift package generate-xcodeproj` as a workaround.

See error below:
![Screenshot_2020-05-15_at_16-1 45 37](https://user-images.githubusercontent.com/1882080/82197895-6d830780-98f3-11ea-8577-068a2dd0ea71.png)

The workaround described in this SO [answer](https://stackoverflow.com/a/59625008) works. I had to manually add those search paths into the FluentBenchmark target of my project.

It would be nice, if `FluentBenchmark` could avoid using `XCTUnwrap` until all these issues are fixed.

**Comment by gwynne** [comment]
Will fix this as soon as I have a few minutes to spare.

**Comment by valeriomazzeo** [comment]
@tanner0101 @gwynne it looks like there are more `XCTUnwrap` calls that have not been removed, at least on the `gm` branch in `MigratorTests.swift`.

![Screenshot 2020-05-29 at 10 24 56](https://user-images.githubusercontent.com/1882080/83244078-c2960780-a196-11ea-9fdd-38aa1cac9fde.png)
