### ISSUE TITLE
Driver error leaks

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/fluent-kit#281]
Fluent is currently throwing errors from its underlying driver.

As Fluent is meant to be an abstract layer (as in: a module using Fluent shouldn't care about what driver is being used), this doesn't allow for errors to be handled.

For example:

Trying to save a a record with an already existing key using mongo driver, throws a `MongoKitten.InsertError`.

Instead, it would possibly be a better practice to receive a `FluentError.duplicatedKey`.

This would allow the module that uses Fluent, to handle fluent errors without having to import the driver specific headers.

**Comment by tanner0101** [comment]
This is now possible with the `DatabaseError` error protocol in Fluent 4. 

```swift
do {
    try Category(name: "a").create(on: self.database).wait()
    XCTFail("Duplicate save should have errored")
} catch let error as DatabaseError where error.isConstraintFailure {
    // pass
}
```
