### ISSUE TITLE
FluentBenchmark assumes nested objects are always flattened joined by `_`

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/fluent-kit#282]
I am implementing the DatabaseSchema in my mongo driver to take advantage of Mongo schema validator.

This works nicely but there are some assumptions made in FluentBenchmark which prevent me from using it.

In [TestGroup.GroupMoonMigration](https://github.com/vapor/fluent-kit/blob/master/Sources/FluentBenchmark/Tests/GroupTests.swift#L116-L126) all fields are defined this way:
```swift
private struct GroupMoonMigration: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.schema("moons")
            .field("id", .uuid, .identifier(auto: false))
            .field("name", .string, .required)
            .field("planet_name", .string, .required)
            .field("planet_type", .string, .required)
            .field("planet_star_name", .string, .required)
            .field("planet_star_galaxy_name", .string, .required)
            .create()
    }
```

As a result my mongo schema validator looks like this:
```json
{
  $jsonSchema: {
    bsonType: 'object',
    required: [
      'name',
      'planet_name',
      'planet_type',
      'planet_star_name',
      'planet_star_galaxy_name'
    ],
    properties: {
      _id: {
        bsonType: 'binData'
      },
      name: {
        bsonType: 'string'
      },
      planet_name: {
        bsonType: 'string'
      },
      planet_type: {
        bsonType: 'string'
      },
      planet_star_name: {
        bsonType: 'string'
      },
      planet_star_galaxy_name: {
        bsonType: 'string'
      }
    }
  }
}
```

Although, when [seeding the test data](https://github.com/vapor/fluent-kit/blob/master/Sources/FluentBenchmark/Tests/GroupTests.swift#L137-L162) they are all specified as nested objects:

```swift
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        let moon = GroupMoon(
            name: "Moon",
            planet: .init(
                name: "Earth",
                type: .smallRocky,
                star: .init(
                    name: "Sun",
                    galaxy: .init(name: "Milky Way")
                )
            )
        )
        let europa = GroupMoon(
            name: "Moon",
            planet: .init(
                name: "Jupiter",
                type: .gasGiant,
                star: .init(
                    name: "Sun",
                    galaxy: .init(name: "Milky Way")
                )
            )
        )
        return moon.save(on: database)
            .and(europa.save(on: database))
            .map { _ in }
    }
```

I suppose this works in the SQL drivers because the driver itself, flatten those nested objects by concatenating the various namespaces with `_`. Although, this is an implementation details, and the tests shouldn't rely on it.

In this specific example using mongo, those objects are instead nested properly, therefore the validation fails.

**Comment by tanner0101** [comment]
`@Group` works by flattening the structure and joining keys using `_`. On `master`, this behavior is dynamic and depends on the underlying driver to decide. On `gm`, this has been changed to be consistently flat (using `_`) and that will be how it works for release. I'd recommend working off the `gm` branch for the time being. It should be released as the 1.0.0 tag soon.

**Comment by valeriomazzeo** [comment]
Maybe I am doing something wrong, but that `gm` branch doesn't compile.
![Screenshot 2020-05-29 at 00 33 02](https://user-images.githubusercontent.com/1882080/83204538-001d7500-a144-11ea-9387-e8ec63a0a8b6.png)

**Comment by tanner0101** [comment]
Run `swift package update` to get the latest version of SQLKit.
