### ISSUE TITLE
Migrations should be wrapped in a transaction

### ISSUE THREAD

**Issue by ileitch** [vapor/fluent-kit#286]
Migrations are typically not idempotent, and thus should be performed within a transaction. Given a migration consisting of multiple statements, and when one of the middle statements results in an error, the migration cannot be re-run or reverted.

**Comment by tanner0101** [comment]
This would be great, but not all of the underlying database drivers support DDL (which is most common in migrations) in transactions. See https://stackoverflow.com/questions/20420600/laravel-migration-transaction for more information. 

Quoting Taylor Otwell from a [similar issue](https://github.com/laravel/framework/issues/302):

> Yeah, there is still no really solid solution to this. My best advice is to do a single operation per migration so that your migrations stay very granular.
