### ISSUE TITLE
Having

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent-kit#31]
Migrated from https://github.com/vapor/fluent/issues/585.

The `QueryBuilder` type should somehow allow queries with the `HAVING` keyword. This keyword more or less allows aggregation of rows after the `WHERE` clause.

See the [W3C page](https://www.w3schools.com/sql/sql_having.asp) for more information.

**Comment by SijmenSchoon** [comment]
Guess it makes sense that I pick this one up too

**Comment by tanner0101** [comment]
FluentKit doesn't support "group by" yet so we would need to add that first at least. But I'm still not sure I understand how either of these work in the context of models / query builder. It seems like we need to consider use cases first and how this would tie in with the model API.

**Comment by calebkleveter** [comment]
@tanner0101 Here is an example of where I needed `GROUP BY` and `HAVING`, but had to roll my own mini query constructor because Fluent didn't have it yet. I hope the coed is readable 😄:
https://github.com/SwiftCommerce/ProductManager/blob/master/Sources/App/Models/Product/Product%2BFilter.swift

**Comment by tanner0101** [comment]
@calebkleveter do you think you could summarize the concept here? That's quite a bit of code to parse haha

**Comment by tanner0101** [comment]
Mainly what I'm wondering about is how do you access the results of this query that uses group by / having. Were you able to decode it into a `Model` or did you need a custom data type to decode it?

**Comment by tanner0101** [comment]
@calebkleveter ah i see. This makes a bit more sense. Isn't this essentially what `unique()` would do? Maybe this wouldn't even be a problem in Fluent 4 because only `Product`'s fields would be selected in the first place so `SELECT DISTINCT` should work

**Comment by calebkleveter** [comment]
The problem with `SELECT DISTINCT` is that it requires the whole rows to be identical, which will never happen due to matching IDs. Also, that wouldn't remove the need for the `HAVING` statement.

**Comment by tanner0101** [comment]
Ok I re-read your issue and I understand the problem better now. If I am understanding, what you're effectively trying to do here is get all Products that have _two_ specific attribute siblings: one with `color = blue` and another one with `food = false`. 

So in an ideal Fluent, that might look like this:

```swift
let products = Product.query(on: db)
    .join(\.$attributes)
    .filter(group: .or) { 
        $0.filter(\Attribute.$key == "color").filter(\Attribute.$value == "blue") 
    }.filter(group: .or) { 
        $0.filter(\Attribute.$key == "food").filter(\Attribute.$value == "borger") 
    }.filter(each: \.$attributes, has: .count(greaterThan: 2))
```

Does this make sense? Basically what I'm trying to get at here is framing these types of things in the context of "what is the Model API lacking?" not "what SQL feature is Fluent lacking?". In other words, what are the _semantics_ of what you are trying to do here. Not which SQL keyword did you use to do it. 

This kind of rigorous thinking is especially important when it comes to MongoDB support which is being actively worked on for Fluent 4.
