### ISSUE TITLE
Allow @Field to define a default value

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/fluent-kit#317]
For NoSQL databases it's useful to be able to specify a property using `@Field` and at the same time provide a default value. I.e.: `@Field(key: "myString", default: "abc")`.

**Comment by tanner0101** [comment]
This can be achieved pretty easily with Swift, for example:

```swift
@OptionalField(key: "my_string")
var myString: String?

var myStringOrDefault: String {
    self.myString ?? "myDefault"
}
```
