### ISSUE TITLE
Auto Generating Migrations

### ISSUE THREAD

**Issue by JiaWeiXie** [vapor/fluent-kit#330]
Any thoughts or possible on creating command to autogenerate migration?

something like python

[Django](https://docs.djangoproject.com/en/3.0/topics/migrations/) `manage.py makemigrations`

[sqlalchemy](https://alembic.sqlalchemy.org/en/latest/autogenerate.html) `alembic revision --autogenerate -m "Added account table"`

I think that can reduce complexity to start using ORM.

**Comment by tanner0101** [comment]
Yes, this is something I'd definitely like to explore. There's already an issue for it here (https://github.com/vapor/toolbox/issues/176). It's on vapor/toolbox since it would likely be a command-line tool. Thanks!
