### ISSUE TITLE
CodingKeys don't work on class that inherits Model / Content

### ISSUE THREAD

**Issue by pikzelz** [vapor/fluent-kit#331]
### Steps to reproduce
Create a class like below:
```
final class Item : Model, Content {
    enum CodingKeys: String, CodingKey {
        case title,
        case publishedAt = "published_at"
    }

    @ID
    var id: UUID?

    @Field(key: "title")
    var title: String

    @Field("published_at")
    var publishedAt: Date
}
```

If you then try to send a post request to create something with a json like this:
```
{
    "title":"hello world",
    "published_at": "2020-06-16 12:00:00"
}
```
Vapor will complain that the field publishedAt is missing. Even though CodingKeys is saying it should transform.

To get it working you would have to send your own JSONDecoder() with .convertFromSnakeCase
When you want to actually see it in the response you would need to implement `encode(to encoder: Encoder)`

When using a struct it does work, however, this doesn't work in combination with Model as that's class bound, maybe I'm missing something. But I couldn't find anything in the docs about this.

### Expected behavior
It would be automatically using CodingKeys without the need of using a custom JSONDecoder or overwriting encode(to:).

### Actual behavior
Keeping the keys cameCase instead of snakeCase

### Environment

* Vapor Framework version: 4.0.0-beta29
* Vapor Toolbox version: 3.1.10 (vapor-beta --version doesn't work)
* OS version: MacOS 10.15.4

**Comment by 0xTim** [comment]
Transferring to FluentKit since that's where the issue lies

**Comment by 0xTim** [comment]
I suspect the answer may be https://docs.vapor.codes/4.0/fluent/model/#data-transfer-object though

**Comment by pikzelz** [comment]
Thank you, I did notice the DTO, I thought it was only used for updating existing records, but not for creating new ones, I'm unsure if it can be used the same way.

**Comment by 0xTim** [comment]
Yeah definitely, you can have a `CreateItem` type that contains the data as you expect and then convert that to an `Item`. This is useful if you want to have a `CreateUser` type that has a `password` and `confirmPassword` field, or fields in the DB that are set automatically.

To be clear - I think the fact that you can't override the `CodingKeys` is still an issue that should be resolved

**Comment by pikzelz** [comment]
Thank you, this pointed me in the right way to get it working the way I want. I also still feel that `CodingKeys` should be supported, however, this workaround is also a great solution.

**Comment by tanner0101** [comment]
Swift doesn't currently give us any way to access the compiler generated `CodingKeys` (or any CodingKeys really). This means we must rely on the values we get from `Mirror` to achieve this.

As @0xTim, using DTOs is the smart move here. That gives you full control over the structure of your app's API without needing to tie yourself to the DB structure. The next version of Fluent is likely to rely even more on DTOs, too (assuming the `StoredPropertyIterable` protocol finally comes to fruition).
