### ISSUE TITLE
Bug: Manual ID is overriden by query builder by "DEFAULT"

### ISSUE THREAD

**Issue by gmcadosch** [vapor/fluent-kit#332]
I'm trying to save an array of models that have manually set the "ID" field in the models as the ID field is NOT set to autoincrement.

Unfortunately, it seems that there's a bug as Fluent gives me a error "[ ERROR ] null value in column "id" violates not-null constraint (ExecConstraints)".

I've debugged my code: the ID fields of the models in the array are properly filled. I've then set a breakpoint within the create() function of QueryBuilder.swift. The query object has a customIDKey which is NIL.

The table gets loaded when I'm deleting the primary key on the ID field. The name field is then properly populated in the table, so it's not an issue of the JSON loading.

Here's my model:

    import Fluent
    import Vapor

    final class CodeAddressType: Model, Content {
        static let schema = "code_address_type"
    
        @ID(custom: .id)
        var id: Int?

        @Field(key: "name")
        var name: String

        init() { }

        init(id: Int? = nil, name: String) {
            self.id = id
            self.name = name
        }
    }

Here's the migration:

    database.schema("code_address_type")
        .field("id", .int, .identifier(auto: false))
        .field("name", .string, .required)
        .create(),

**Comment by gmcadosch** [comment]
I've turned "debug" mode on and here's the output. It seems that this is a bug as the ID is set in the model to save, but the query builder is setting it to "DEFAULT":

[CodeAddressType(input: [id: 1000, name: "Liegenschaft"]), CodeAddressType(input: [name: "Objekt", id: 1001]), CodeAddressType(input: [id: 1100, name: "Postadresse"]), CodeAddressType(input: [id: 2000, name: "Telefon"]), CodeAddressType(input: [id: 3000, name: "Email"])]

[ DEBUG ] query create code_address_type input=[[id: default, name: "Liegenschaft"], [id: default, name: "Objekt"], [name: "Postadresse", id: default], [name: "Telefon", id: default], [id: default, name: "Email"]] [database-id: psql] (FluentKit/Query/Builder/QueryBuilder.swift:266)
[ DEBUG ] INSERT INTO "code_address_type" ("id", "name") VALUES (DEFAULT, $1), (DEFAULT, $2), (DEFAULT, $3), (DEFAULT, $4), (DEFAULT, $5) RETURNING "id" ["Liegenschaft", "Objekt", "Postadresse", "Telefon", "Email"] [database-id: psql] (PostgresNIO/PostgresDatabase+Query.swift:124)

**Comment by 0xTim** [comment]
Just for clarity - how are you actually saving your models?

**Comment by gmcadosch** [comment]
I'm using the "create" method on an array of models.

Here's the full code of the migration doing an initial load from a JSON file:

    struct InitialDataMigration: Migration {
        func prepare(on database: Database) -> EventLoopFuture<Void> {
            return loadFromJSON(type: CodeAddressType.self, on: database)
        }

        func revert(on database: Database) -> EventLoopFuture<Void> {
            return database.query(CodeAddressType.self).delete(force: true)
        }

        private func loadFromJSON<T>(type: T.Type, on database: Database) -> EventLoopFuture<Void> where T: Model {
            let path = "/Users/gmc/Development/immoappserver-4/Seed/" + String(describing: T.self) + ".json"
            do {
                let data = try Data(contentsOf: URL(fileURLWithPath: path))
                let decoder = JSONDecoder()
                let codes = try decoder.decode([T].self, from: data)
                print(codes)

                return codes.create(on: database)
            } catch {
                return database.eventLoop.makeFailedFuture(error)
            }
        }
    }
