### ISSUE TITLE
Cannot decode Fluent model from raw query

### ISSUE THREAD

**Issue by grahamburgsma** [vapor/fluent-kit#334]
This is something that worked in Vapor 3 and was surprised when it didn't work with Vapor 4.

I often need more complex queries than Fluent can do, so I resort to a raw sql query. However decoding a fluent model from a raw query does not work with Parent properties.

Let's say I have a model like this:
```swift
class Pet: Model {
    @ID()
    var id: UUID?

    @Parent(key: "ownerID")
    var owner: User
}
```

And try to use a raw query to decode it:
```swift
(req.db as! SQLDatabase).raw("SELECT * FROM Pet").all(decoding: Pet.self)
```

This would give an error of something like:
`Value of type 'User' required for key 'owner'.`

What I would expect to happen is that it would use the `ownerID` key of the Parent field to decode the model.

**Comment by grahamburgsma** [comment]
Since Fluent decoding works much differently than this case would expect, the recommendation is to create a separate type to decode instead.

**Comment by tanner0101** [comment]
This is related to https://github.com/vapor/fluent-kit/issues/224
