### ISSUE TITLE
Disable logging for query

### ISSUE THREAD

**Issue by kennyevo** [vapor/fluent-kit#344]
Hi!

I'm using a unique field to check if an item already in the db, and checking the result in the Future.
Currently I'm logging if an entity is already in the db, but fluent is logging the error by default.

Is it possible to silence the error? Or set a custom logger in vapor4?

Thanks in advance, and sorry if it's a noob question

**Comment by tanner0101** [comment]
You should be able to temporarily set the request's log level to something higher than error (like critical). For example:

```swift
req.logger.logLevel = .critical
doQuery(on: req.db).flatMap {
    req.logger.logLevel = .info
}
```

I've also put up a PR that adds a `logging(to:)` method to `Database` for temporarily overriding the logger. You can use the same method of creating a new logger with its log level changed, but with `logging(to:)` you can more precisely set just the database's logger.

https://github.com/vapor/fluent-kit/pull/345
