### ISSUE TITLE
Provide a way to bypass automatic timestamp behavior.

### ISSUE THREAD

**Issue by ileitch** [vapor/fluent-kit#355]
When writing a data migration it can be useful to avoid automatically setting timestamps.

Some API ideas:

```swift
.create(triggerTimestamp: false)
.update(triggerTimestamp: false)
```

```swift
.disableTimestamp()
.update()
```

```swift
.timestamp(.disabled)
.update()
```

**Comment by gwynne** [comment]
This has been possible via the `on: .none` option on `@Timestamp` for some time now.
