### ISSUE TITLE
Fetch Joined Rows

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent-kit#36]
It should be possible to get the rows of a table that was joined to in a query:

```swift
let query = A.query(on: database).joined(\.b)
```

The `query` type here should be `QueryBuilder<(A, B]>`. If `.first` is called, it should return an `EventLoopFuture<(A, [B])>`.

**Comment by tanner0101** [comment]
Here's the syntax for fetching a joined row: 

```swift
let planets = try Planet.query(on: self.database)
    .join(\.galaxy)
    .all().wait()

for planet in planets {
    let galaxy = try planet.joined(Galaxy.self)
    print(galaxy.name) 
}
```
