### ISSUE TITLE
Check if schema exists

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent-kit#365]
Support a method for checking if a schema / table exists without throwing an error. Current methods used by `_fluent_migrations` and `_fluent_enums` checks to see if querying the table fails. This works, but generates error logs both client side and in the DB.

**Comment by gwynne** [comment]
Checking for existence is insufficient - it is also necessary to check for correct structure, or else to just forge ahead with `IF NOT EXISTS` or its equivalent. Beyond that, this is more a symptom of the larger issue that even the most common and universal database errors ("no such schema", "unique constraint violation", "syntax error", etc. - errors that have useful meaning even when moving between SQL and NoSQL) can't be identified without adding database-driver-specific logic. Interestingly enough, we still don't seem to have an issue filed for that particular problem...
