### ISSUE TITLE
Protocolize SQL{Query,Schema}Converter

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent-kit#366]
Apply dialect-specific behavior at the Fluent -> SQL conversion layer would be easier to do if the `SQL*Converter` types were protocols instead of concrete types. This would allow the SQL dialects to simply override any methods they need to customize without needing to declare new protocol methods. 

Example case: https://github.com/vapor/fluent-mysql-driver/pull/191

**Comment by gwynne** [comment]
It would also be easier if FluentSQL and SQLKit weren't constantly at odds. For Fluent 5, the whole way this works is likely to change (though I don't guarantee anything yet); this issue covers too specific a topic to remain relevant in that context.
