### ISSUE TITLE
Unify column and table level constraints

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent-kit#367]
Not all drivers support column vs. table level constraint syntax. This has already created one issue with MySQL here: https://github.com/vapor/fluent-mysql-driver/pull/191. 

Perhaps FluentKit should not differentiate between these two different types of constraints and let the backend determine how to handle them. The SQL backends might be able to get away with only serializing table-level constraints anyway since those seem to have better support. 

Postgres: https://www.postgresql.org/docs/9.1/sql-createtable.html
MySQL: https://dev.mysql.com/doc/refman/8.0/en/create-table.html
SQLite: https://sqlite.org/lang_createtable.html

**Comment by gwynne** [comment]
In modern versions of PostgreSQL and SQLite there are potentially different semantics (based on database-specific syntax) to field-level vs. table-level constraints, and MySQL also supports both syntaxes (though without distinguishing between them in effect when only one field at a time is involved). I think ignoring the semantic separation would be to conflate the complexity of syntactic differences between SQL dialects with the constraints being at fault.
