### ISSUE TITLE
Implement All Fluent 3 Filter Operators

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent-kit#37]
Right now, only the `==` operator has been implemented for the `QueryBuilder.filter` methods. The rest of the operators from Fluent 3 should be implemented.

**All Drivers**
- [ ] `!=`
- [ ] `~~`

**SQL Specific**
- [ ] `~=`
- [ ] `~~`
- [ ] `=~`

Any that I missed can be added to the list.

**Comment by tanner0101** [comment]
I've added the following operators:

|op|filter method|value|
|-|-|-|
|`==`|`.equal`|`T`
|`!=`|`.notEqual`|`T`
|`>=`|`.greaterThanOrEqual`|`T`
|`>`|`.greaterThan`|`T`
|`<`|`.lessThan`|`T`
|`<=`|`.lessThanOrEqual`|`T`
|`~~`|`.subset(inverse: false)`|`[T]`
|`!~`|`.subset(inverse: true)`|`[T]`
|`~=`|`.contains(inverse: false, .suffix)`|`String`
|`~~`|`.contains(inverse: false, .anywhere)`|`String`
|`=~`|`.contains(inverse: false, .prefix)`|`String`
|`!~=`|`.contains(inverse: true, .suffix)`|`String`
|`!~~`|`.contains(inverse: true, .anywhere)`|`String`
|`!=~`|`.contains(inverse: true, .prefix)`|`String`
