### ISSUE TITLE
Enum Types

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent-kit#39]
There should be support for enum types used as model properties. For MySQL, that would be using an `enum` type, for Postgres, it would be an enum table.

**Comment by tanner0101** [comment]
What are your thoughts on this API?

```swift
enum PlanetType: String, DatabaseEnum {
    static let name = "PLANET_TYPE"
    case smallRocky, gasGiant, dwarf
}

struct Planet: Model {
    @Field var id: Int?
    @Field var name: String
    @Field var type: PlanetType
}

final class CreatePlanet: Migration {
    init() { }
    
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        return PlanetType.create(on: database).flatMap {        
            return Planet.schema(on: database)
                .field(\.id, .int, .identifier(auto: true))
                .field(\.name, .string, .required)
                .field(\.type, .enum(PlanetType.self), .required)
                .create()
        }
    }
    
    func revert(on database: Database) -> EventLoopFuture<Void> {
        return Planet.schema(on: database).delete().flatMap {
            return PlanetType.delete(on: database)
        }
    }
}
```

**Comment by calebkleveter** [comment]
I like that 👍, but I'm not sure I understand why the `PlanetType` enum needs the `name` property.

**Comment by tanner0101** [comment]
@calebkleveter for Postgres, the enum will be saved as a new, custom type to your database, so it needs a name. We could have a sensible default, like the type name lowercased or uppercased, but we should definitely have a way to override that. Just like you can override the table-name for a model.

**Comment by tanner0101** [comment]
This has been added!

**Comment by BeauNouvelle** [comment]
How do we use this now, because the above example doesn't work.

**Comment by tanner0101** [comment]
The PR which added them has working examples: https://github.com/vapor/fluent-kit/pull/178
