### ISSUE TITLE
Composite primary keys

### ISSUE THREAD

**Issue by slashmo** [vapor/fluent-kit#4]
It would be very nice if Fluent would allow the use of composite primary keys. 
I already though about one possible implementation which would involve making `[ID]` conform to `ID`, to then combine multiple `ID`s into one. What do you think about that? 

``` swift
extension Array: ID where Element: ID { }
```

**Comment by tanner0101** [comment]
@slashmo thanks for this feature request. Would you mind also sharing some example use cases for this feature?

**Comment by slashmo** [comment]
Hi @tanner0101, thanks for the quick reply. I can give you one concrete example, but as explained later this could also apply to every pivot table.

## Example: Slack-like workspace system
Slack e.g. uses workspace-based user management, meaning a user creates **one account per workspace**, as opposed to more common systems that would relate one user account to multiple workspaces. As a side-effect, this means that the `email` field of a user cannot be unique.

If you would model such a user management system you may end up with two tables looking like this:

### Users
| Field | Type | Primary Key |
| --- | --- | :-: |
| id | UUID | 🔑 |
| email | String |
| password | String |
| workspace_id | UUID |

### Workspaces
| Field | Type | Primary Key |
| --- | --- | :-: |
| id | UUID | 🔑 |
| name | String |

❌ With this database schema, you could not prevent multiple users with the same email pointing to the same workspace.

Instead of using a surrogate primary key (`id`) for the `users` table, a composite primary key containing both `email` and `workspace_id` would ensure that the **combination cannot exist more than once**.

This basically applies to every part of a database where one column is not enough to ensure the uniqueness of a row, which also includes pivot tables.

## Usage in code
``` sql
CREATE TABLE users (
    // ...
    PRIMARY KEY (email, workspace_id)
);
```

To be fair, I haven't thought about the possible implementation in Fluent myself, but it would basically require to have an ID type that could include two or more fields of a model. As written before, maybe allowing an array of `ID`s to be an `ID` itself could make sense.

**Comment by tanner0101** [comment]
Thanks for the detailed response. This makes sense now. I'll think more about how this could be implemented in Fluent and, if the API seems reasonable, we can target Fluent 4.

**Comment by tanner0101** [comment]
Btw, do you have any examples of other ORMs that you use something like this in?

**Comment by slashmo** [comment]
Sounds good 👌

I haven't verified the following ORMs myself, but they all allow for the use of composite keys:

## Native support
- [Hybernate](https://vladmihalcea.com/the-best-way-to-map-a-composite-primary-key-with-jpa-and-hibernate/) (Java)
- [SQLAlchemy](https://docs.sqlalchemy.org/en/latest/faq/ormconfiguration.html#faq-mapper-primary-key) (Python)
- [GORM](http://gorm.io/docs/composite_primary_key.html) (Go)
- [Diesel](https://github.com/diesel-rs/diesel/pull/417) (Rust)

## Support through third-party libraries
- [Eloquent](https://github.com/mopo922/LaravelTreats/tree/master/src/Model) (Laravel / PHP)
- [ActiveRecord](https://github.com/composite-primary-keys/composite_primary_keys) (Rails / Ruby)

I think especially the Hybernate solution is interesting, where they use an additional class to model the ID which then is used inside the "real" model class.

I'd also be happy to contribute to the implementation of this, although I don't have much experience with Fluent's internals yet.

**Comment by groue** [comment]
The GUI-oriented library GRDB also supports composite primary keys, including in its support for [associations](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md) (relationships between records).

**Comment by mxcl** [comment]
+1’d but commenting to add I have an actual production table with a composite key, Fluent is ok with specifying one of them to be *the* primary key and nothing seems broken, but it feels risky to me.

**Comment by slashmo** [comment]
@mxcl Interesting. In that case the production table wasn't created by Fluent, right? 
Because although consuming a table with composite primary keys might work (in your case), using Fluent migrations to create it would require some sort of API support from Fluent itself.

**Comment by mxcl** [comment]
Yeah it was a database I inherited and then built Vapor on top of.

**Comment by tanner0101** [comment]
Referencing this discussion here: https://github.com/vapor/fluent-kit/pull/83#discussion_r337807661

**Comment by linqingmo** [comment]
Inspired by [Hybernate](https://vladmihalcea.com/the-best-way-to-map-a-composite-primary-key-with-jpa-and-hibernate/). Any help will be appreciate. Thanks.
```swift
public protocol AnyMultiField {
    init()
}

extension AnyMultiField {
    var fields: [AnyField] {
        Mirror(reflecting: self).children.compactMap { $1 as? AnyField }
    }
}

extension AnyMultiField where Self: Encodable {
    public func encode(to encoder: Encoder) throws {
        try fields.forEach { try $0.encode(to: encoder) }
    }
}

extension AnyMultiField where Self: Decodable {
    public init(from decoder: Decoder) throws {
        self.init()
        try fields.forEach { try $0.decode(from: decoder) }
    }
}

public protocol Model: AnyModel {
    associatedtype IDValue: Codable, Hashable

    var id: IDValue { get set }
}

protocol AnyID {
    var exists: Bool { get set }
    var cachedOutput: DatabaseOutput? { get set }
}

@propertyWrapper
public final class CompositeID<Value>: AnyID, AnyProperty
    where Value: AnyMultiField & Hashable
{
    public var projectedValue: CompositeID<Value> {
        return self
    }
    
    public var exists: Bool
    
    var cachedOutput: DatabaseOutput?
    public var wrappedValue: Value
    
    public init() {
        wrappedValue = Value()
        exists = false
    }
    
    public func output(from output: DatabaseOutput) throws {
        self.exists = true
        self.cachedOutput = output
        try wrappedValue.fields.forEach { try $0.output(from: output) }
    }
    
    func encode(to encoder: Encoder) throws {
        try wrappedValue.fields.forEach { try $0.encode(to: encoder) }
    }
    
    func decode(from decoder: Decoder) throws {
        try wrappedValue.fields.forEach { try $0.decode(from: decoder) }
    }
}
```

```swift
public final class Employee: Model, Content {
    public struct ID: AnyMultiField, Hashable, Codable {
        @Field(key: "company_id")
        public var companyId: Int
        
        @Field(key: "employee_number")
        public var employeeNumber: Int
        
        public init() {}
        
        public init(companyId: Int, employeeNumber: Int) {
            self.companyId = companyId
            self.employeeNumber = employeeNumber
        }
        
        public static func == (lhs: Self, rhs: Self) -> Bool {
            return lhs.companyId == rhs.companyId && lhs.employeeNumber == rhs.employeeNumber
        }
        
        public func hash(into hasher: inout Hasher) {
            hasher.combine(companyId)
            hasher.combine(employeeNumber)
        }
    }
    
    @CompositeID
    public var id: ID
    
    @Field(key: "name")
    public var name: String
    
    public static let schema: String = "Employees"
    
    public init() {}
    
    public init(companyId: Int, employeeNumber: Int, name: String) {
        self.id = ID(companyId: companyId, employeeNumber: employeeNumber)
        self.name = name
    }
}
```

**Comment by slashmo** [comment]
@linqingmo Nice to see progress towards resolving this. I think `Equatable` and `Hashable` conformance for the `ID` type could even be generated by the compiler, that way the nested `ID` struct would look pretty clean. Overall the public API looks pretty nice IMHO.

**Comment by tanner0101** [comment]
That's an interesting approach. How does this interact with `Employee.find(_:on:)` and the `_$id` extension?

**Comment by linqingmo** [comment]
```swift
protocol AnyID: AnyObject {
    ...
    
    func filter<Model: FluentKit.Model>(_ builder: QueryBuilder<Model>, _ id: Model.IDValue) -> QueryBuilder<Model>
}

@propertyWrapper
public final class ID<Value>: AnyID, AnyField, FieldRepresentable
    where Value: Codable
{
    ...
    func filter<Model: FluentKit.Model>(_ builder: QueryBuilder<Model>, _ id: Model.IDValue) -> QueryBuilder<Model> {
        return builder.filter(field.key, .equality(inverse: false), id)
    }
}

@propertyWrapper
public final class CompositeID<Value>: AnyID, AnyProperty
    where Value: AnyMultiField & Hashable
{
    ...
    func filter<Model: FluentKit.Model>(_ builder: QueryBuilder<Model>, _ id: Model.IDValue) -> QueryBuilder<Model> {
        guard let id = id as? Value else { return builder }
        id.fields.forEach { field in
            guard let value = field.inputValue else { return }
            builder.filter(.field(path: [field.key], schema: Model.schema, alias: nil), .equality(inverse: false), value)
        }
        return builder
    }
}
```
Will this help?

**Comment by linqingmo** [comment]
`AnyMultiField` can also use to structure fields, it can reduce code without subclass.
```swift
struct Coordinate2D: AnyMultiField {
    @Field(key: "latitude")
    var latitude: Double
    @Field(key: "longitude")
    var longitude: Double
}

final class A: Model {
   @MultiField var coordinate: Coordinate2D
}
    
final class B: Model {
   @MultiField var coordinate: Coordinate2D
}
```

**Comment by patchthecode** [comment]
is this still being worked on>

**Comment by 0xTim** [comment]
This is not something we're actively working on. We might add it as a consideration for Fluent 5 but we're open to community contributions if you add to add it

**Comment by Remi-C** [comment]
Hey folks, just a +1 here for this feature.
Composite primary keys are a staple of any large/scalable database, as they allow partitioning/sharding/distributing the data.
They also have significant advantages as soon as you table is > ~10M rows.
Composite keys are required for some pretty common foreign keys usages constraints , pivot tables being a good example.
Yes you can always generate a new uuid per row instead of using a composite primary key, but it can be dangerous/bad practice.
To give a swift analogy, it would be the difference between
 -  having a class with 2 properties, each with own name, type, default, ... 
 - vs bundling these 2 properties into one single property that concatenates both values.
 It can works, but you loose a lot : type check, handling null values, extensibility, handling non-trivial types, etc.
 In the pivot table case, it's similar. It can work, but we loose a lot (efficiency, constraint, scaling, portability, reproducibility, deterministic behavior, harder permissions, etc.)

**Comment by rausnitz** [comment]
If this does move forward at some point, consider using `Set<ID>` instead of `Array<ID>`. A composite primary key shouldn't have any column repeated, and I don't think the order of the columns matters.

**Comment by cristiancardosodexcom** [comment]
It needs some documentation, there is not document in https://docs.vapor.codes/fluent/model/ that talks about @CompositeID

**Comment by zamderax** [comment]
Here's what I did

```swift
final class Organization: Model, @unchecked Sendable {
    static let schema = "organizations"

    @ID(custom: "organization_id")
    var id: String?

    @Field(key: "name")
    var name: String

    @Field(key: "details")
    var details: String

    @Field(key: "domain")
    var domain: String?

    @Timestamp(key: "created_at", on: .create)
    var createdAt: Date?

    @Timestamp(key: "updated_at", on: .update)
    var updatedAt: Date?

    init() {}

    init(id: String?, name: String, details: String, domain: String, createdAt: Date?, updatedAt: Date?) {
        self.id = id
        self.name = name
        self.details = details
        self.domain = domain
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

final class User: Model, @unchecked Sendable {
    static let schema = "users"

    @ID(custom: "email")
    var id: String?

    @Field(key: "name")
    var name: String

    init() {}

    init(id: String?, name: String) {
        self.id = id
        self.name = name
    }
}

final class Member: Model, @unchecked Sendable {
    static let schema = "members"

    final class MemberID: Fields, Hashable, @unchecked Sendable {
        @Parent(key: "user_id") var user: User
        @Parent(key: "organization_id") var organization: Organization
        
        init() {}
        init(userID: User.IDValue, organizationID: Organization.IDValue) { (self.$user.id, self.$organization.id) = (userID, organizationID) }
        static func == (lhs: IDValue, rhs: IDValue) -> Bool { lhs.$user.id == rhs.$user.id && lhs.$organization.id == rhs.$organization.id }
        func hash(into hasher: inout Hasher) { hasher.combine(self.$user.id); hasher.combine(self.$organization.id) }
    }

    @CompositeID
    var id: MemberID?

    @Field(key: "role")
    var role: String

    init() {}

    init(id: MemberID, role: String) {
        self.id = id
        self.role = role
    }
}
```

You can find this better in the test cases here:

https://github.com/vapor/fluent-kit/blob/2cceea25d3e8e7bfc038e1022e24a51c4599bdb8/Tests/FluentKitTests/CompositeIDTests.swift#L399C1-L420C2
