### ISSUE TITLE
Querybuilder's all() can't be compiled with an argument

### ISSUE THREAD

**Issue by rurza** [vapor/fluent-kit#404]
fluent-kit 1.10, Swift 5.3
It looks that for some reason Swift compiler can't find a method .all() with a keypath.
When a field is provided, the compiler says that it can't infer it and suggests to specify the root object and when it's provided it says that argument is passed to a call that takes no arguments

**Comment by rurza** [comment]
Oh, I didin't notice that this method isn't available and the [docs](https://docs.vapor.codes/4.0/fluent/query/#unique) lie :(

**Comment by 0xTim** [comment]
It should do - it's in [FluentKit](https://github.com/vapor/fluent-kit/blob/master/Sources/FluentKit/Query/Builder/QueryBuilder.swift#L163)

**Comment by rurza** [comment]
Looked like a some compiler hiccup!
