### ISSUE TITLE
[Question]: Is there a way to form a @Group of fields including @Timestamp ?

### ISSUE THREAD

**Issue by bitwit** [vapor/fluent-kit#409]
I'm trying to figure out if there's a way to apply  created/updated/deleted timestamps to all my models without excessive repetition, but it appears that @Timestamp only functions directly inside of a model definition. Is there a way to accomplish this right now or is this just a limitation?

I tried subclassing from a common model but that also appears to be a no-no.

Thanks in advance, I'm loving these APIs so much.

**Comment by 0xTim** [comment]
Unfortunately there's no real good way to do this. You can use a protocol to ensure that you have the properties as part of your models, but you still need to define them in each one. And subclassing really doesn't mix with Fluent as you may have found out!

**Comment by bitwit** [comment]
Thanks for confirming. I'll keep it simple for now
