### ISSUE TITLE
FluentKit Fails to Build with Xcode 12.5 Beta 1 (Swift 5.4)

### ISSUE THREAD

**Issue by rnantes** [vapor/fluent-kit#415]
### Steps to reproduce the behavior:
1. Build 'master' branch with Xcode 12.5 Beta 1
2. See errors such as `Value of type 'EnumMetadata' has no member '$name'`

### Note
I think I've narrowed it down to some of the generic code for property wrappers similar to: `typealias Field<Value> = FieldProperty<Self, Value> where Value: Codable, Self: Fields` in which the `projectedValue` of `@FieldProperty` is not propagating to `@Field` when using the property wrapper like: `@Field(key: "name")`. However, I found that if I directly use the `@FieldProperty` property wrapper it works i.e: @FieldProperty<EnumMetadata, String>(key: "name")' I can get past some of the errors.

Here is the line I am referring to:
https://github.com/vapor/fluent-kit/blob/master/Sources/FluentKit/Properties/Field.swift#L1-L4

**Comment by rnantes** [comment]
Looks like this is the same issue: https://bugs.swift.org/browse/SR-14143
and may be solved with this PR that was just merged: https://github.com/apple/swift/pull/35726

**Comment by siemensikkema** [comment]
@rnantes Closing this issue for now under the assumption the Swift PR fixes our issue. Please re-open if it doesn't! 🙏🏻

**Comment by 0xTim** [comment]
Just to confirm, this is fixed in `swiftlang/swift:nightly`
