### ISSUE TITLE
Enum creation method returning EventLoopFuture<Void>

### ISSUE THREAD

**Issue by vaclav-broz** [vapor/fluent-kit#418]
**Problem:**
I would like to have migrations only for creation of one database enum. However in current implementation the `create()` method on `EnumBuilder` returns `EventLoopFuture<DatabaseSchema.DataType>` and the `prepare(on database: Database)` method on migration should return value of type `EventLoopFuture<Void>` so I have to chain `transform(to: ())` on the `EnumBuilder` `create()` which is a bit cumbersome.

**Solution:**
I suggest to create second `create()` method on `EnumBuilder` which would just create the enum and return `EventLoopFuture<Void>`.

**Alternatives:**
I did not come up with any other idea how to solve the problem described above.

**Comment by 0xTim** [comment]
I think this is likely to cause more problems than it's worth with the type inference engine with the same signature and a different return type. Additionally, even with a differently named function, adding additional API surface to avoid having to call `.transform(to: ())` in some cases is not worth it IMO

**Comment by vaclav-broz** [comment]
I think you are right. Sorry for coming up with a kind of silly idea.
