### ISSUE TITLE
Public initializer for TimestampFormatFactory

### ISSUE THREAD

**Issue by rawillk** [vapor/fluent-kit#421]
Unfortunately dates not alway have correct formats in legacy databases.
It would be convenient to be able to create custom ***TimestampFormat*** implementations and use it with ***@Timestamp***.
It does not seems to be possible due to ***TimestampFormatFactory*** initializer access level (it's internal by default)

**Comment by 0xTim** [comment]
I'd be happy to open this up to be public for a use case like this if you want to do a PR
