### ISSUE TITLE
Impossible to use Field operator in a query with a @Group field property wrapper

### ISSUE THREAD

**Issue by KalouH** [vapor/fluent-kit#443]
### Describe the bug

According to the documentation : 

Field 

By default, all of a model's fields will be read from the database by a query. You can choose to select only a subset of a model's fields using the field method.

If we try to use field on a a field declared as @Group the compilation failed.
 
Instance method 'field' requires that 'GroupProperty<Spot, Adress>' conform to ‘QueryableProperty’

### To Reproduce

1. Add package with configuration '...'
2. Send request with options '...'
3. See error

### Environment

final class Adress : Codable, Fields {
    
    @Field(key: "cp")
    var cp : Int?
    
    @Field(key:"street")
    var street : String?
    
    @Field(key: "city")
    var city : String?
    
    @Field(key: "region")
    var region : String?
    
    init() {}

}

final class Spot  : Codable, Content, Model {
    
    static var schema: String = "spot2"
    
    @ID()
    var id : UUID?
    
    @Field(key: "start")
    var start : GeometricPoint2D?
    
    @Group(key: "Adress")
    var adress : Adress
    
 }
 
 
 let builder  = ex.query(on: req.db(.spoty)).filterGeometryWithin(\.$start, polygon)
             .field(\.$id)
             .field(\.$adress)

* Vapor Framework version: No Framework 
* Vapor Toolbox version: 18.3.2
* OS version: 11.4 on Mac M1

Fluent : 4.3.1
fluent-kit : 1.13.0
fluent-postresdriver : 2.1.2
postgres-kit : 2.3.0

**Comment by gwynne** [comment]
This is not a bug; `@Group` can not be directly addressed as a queryable property because it does not represent any single database field. Instead, the correct behavior is to specify the individual fields of the `@Group`, e.g. `.field(\.$adress.$cp)` etc.
