### ISSUE TITLE
Async/await ModelMiddleware doesn't work

### ISSUE THREAD

**Issue by kevinrenskers** [vapor/fluent-kit#446]
I am working with the async-await branches of both Vapor and FluentKit, and overall it's all working perfectly fine and really improves the DX of working with Vapor. Well done!

However, the ModelMiddelware isn't working properly.

Old-fashioned is working fine:

``` swift
struct CampaignModelMiddleware: ModelMiddleware {
  func update(model: Campaign, on db: Database, next: AnyModelResponder) -> EventLoopFuture<Void> {
    return next.update(model, on: db).map {
      print ("Campaign \(model.name) was updated")
    }
  }
}
```

But the async/await version is not:

``` swift
struct CampaignModelMiddleware: ModelMiddleware {
  func update(model: Campaign, on db: Database, next: AnyModelResponder) async throws {
    try await next.update(model, on: db).get()
    print("Campaign \(model.name) was updated")
  }
}
```

It's never executed. I think the problem is that while the protocol methods and their default implementation are given, those methods are never actually called from within the [`ModelMiddleware.handle` method](https://github.com/vapor/fluent-kit/blob/async-await/Sources/FluentKit/Middleware/ModelMiddleware.swift#L38).

**Comment by elidydev** [comment]
I would like to take a look at this one

**Comment by 0xTim** [comment]
@elidydev awesome!
