### ISSUE TITLE
Error with async/await transaction

### ISSUE THREAD

**Issue by velascopja** [vapor/fluent-kit#464]
Hi,

first of all, sorry if this isn't the place to post this.

I'm following the Vapor documentation to learn how to use this amazing framework. When I try the code in Vapor: Fluent -> Transactions, I get 1 error ("Generic parameter 'T' could not be inferred") and 2 warnings ("No 'async' operations occur within 'await' expression" and "No calls to throwing functions occur within 'try' expression") in this line of code:
```swift
let transaction = try await req.db.transaction
```
Here is the code:
```swift
app.post("transactions") { req async throws -> HTTPStatus in
        var sun = Star(name: "Sun", galaxyID: UUID("65b68ea0-cdb0-418b-9136-f31fca833356")!)
        var sirius = Star(name: "Sirius", galaxyID: UUID("65b68ea0-cdb0-418b-9136-f31fca833356")!)
        let transaction = try await req.db.transaction
        try await sun.save(on: transaction)
        try await sirius.save(on: transaction)
        return .ok
    }
```
Could you tell me what I'm doing wrong?

Thanks in advance!

**Comment by velascopja** [comment]
Thanks to Roland Lariotte in stackoverflow I've realised that when I 'Jump to Definition' in XCode from ```save(on:)``` in ```sirius``` or ```sun```, it takes me to this method:

```swift
public func save(on database: Database) -> EventLoopFuture<Void> {
        if self._$id.exists {
            return self.update(on: database)
        } else {
            return self.create(on: database)
        }
    }
```
which is not an async method. This method is included in 
```swift
extension Model
```
inside Model/Model+CRUD.swift file, which is not the one I'm intended to use.

I guess the one I'd like to use is this:
```swift
func save(on database: Database) async throws {
        try await self.save(on: database).get()
    }
```
which is included in
```swift
@available(macOS 12, iOS 15, watchOS 8, tvOS 15, *)
public extension Model
```
inside Concurrency/Model+Concurrency.swift file.

I use 
```swift
import Fluent
import Vapor
```
in my file routes.swift where ```app.post("transactions")``` is.

Anyone knows what am I doing wrong?

**Comment by velascopja** [comment]
If I change 
```
        let transaction = try await req.db.transaction
        try await sun.save(on: transaction)
        try await sirius.save(on: transaction)
```
with
```
        try await req.db.transaction { transaction in
            try await sun.save(on: transaction)
            try await sirius.save(on: transaction)
        }
```
Anyone knows why?

Thanks in advance!

**Comment by 0xTim** [comment]
The docs are wrong and have now been updated

**Comment by velascopja** [comment]
Great!

Thank you very much!!!
