### ISSUE TITLE
MySQL CONSTRAINT/KEY logic result in error when trying to delete a constraint

### ISSUE THREAD

**Issue by kevinzhow** [vapor/fluent-kit#491]
https://github.com/vapor/fluent-kit/blob/9d47c328bf83999968c12a3bc94ead1d706ad4a9/Sources/FluentSQL/SQLSchemaConverter.swift#L280

This CONSTRAINT/KEY logic result in this issue https://github.com/vapor/fluent/issues/722 which will made `deleteConstraint` didn't work

Wondering why we have this logic and do we have any unit test on this?

**Comment by gwynne** [comment]
This was handled more comprehensively in #522
