### ISSUE TITLE
Shouldn't use `model.id!` but `guard let id = model.id` 

### ISSUE THREAD

**Issue by hyouuu** [vapor/fluent-kit#495]
### Describe the bug

The codebase uses lots of `model.id!` e.g. https://github.com/vapor/fluent-kit/blob/main/Sources/FluentKit/Model/Model%2BCRUD.swift#L74, and if a model was newly created using a custom `init` without generating the `id` yet (e.g. on iOS client), accessing `model.id!` causes instant crash. Instead, we should `guard` and throw an exception.

### To Reproduce

1. Add a model and a custom `init`, and don't manually assign a value to `id`
2. Call `model.delete()`

### Expected behavior

An exception should be thrown as `delete` etc are throwing functions

### Environment

I'm using `fluent-sqlite-driver` of `main` branch via SPM in Xcode on iOS 15.4, which depends on `FluentKit`

* Vapor Framework version: NA
* Vapor Toolbox version: NA
* OS version: macOS 12.3

**Comment by ahmdyasser** [comment]
How can I assign this issue to myself?

**Comment by 0xTim** [comment]
@ahmdyasser you should be able to assign yourself in the top right. I'll assign it to you for now
