### ISSUE TITLE
watchOS support

### ISSUE THREAD

**Issue by hyouuu** [vapor/fluent-kit#500]
**Is your feature request related to a problem? Please describe.**
I'm currently using Fluent for my backend and iOS/macOS client, and would like to extend into my watchOS client. However, currently FluentKit is not supporting watchOS

**Describe the solution you'd like**
FluentKit support watchOS

**Describe alternatives you've considered**
I could use GRDB, CoreData etc, but would love to still use FluentKit

**Comment by krippz** [comment]
I'll have a go at this
