### ISSUE TITLE
Singleton Models

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent-kit#51]
This would limit the database table so it can only contain 1 row. It would either be implemented by conforming your model `SingletonModel`, or a `singleton()` method on the `SchemeBuilder` type and you have to create a custom migration.

**Comment by tanner0101** [comment]
This should already be do-able with existing API. You can have something like:

```swift
final class Singleton: Model {
    static let id = UUID(string: ...)
    @ID var id: UUID?
    @Field ...
}

extension Singleton: Model {
    static func get(on db: Database) -> ELFuture<Singleton> {
        self.find(self.id, on: db).unwrap(or: ...)
    }
}
```

Let me know if I'm missing something obvious.

**Comment by calebkleveter** [comment]
SQL has constraints that can be added to the table to enforce singleton behaviour, so I think it would make sense if that could be added. Though, that might be an addition for SQLKit and not FluentKit as I don't think NoSQL databases support this feature.
