### ISSUE TITLE
@Group causing fatal error

### ISSUE THREAD

**Issue by haIIux** [vapor/fluent-kit#530]
### Describe the bug

When attempting to POST to a model in which contains a `@Group` as outlined [within this Gist](https://gist.github.com/haIIux/238263627231af10cfa93152810f4b64) it causes a fatal error on line 71 within the `Group.swift` file of FluentKit v1.35.0.

```swift
    public func input(to input: DatabaseInput) {
        self.value!.input(to: input.prefixed(by: self.prefix))
    }
```

### To Reproduce

Utilize the gist linked above and attempt to POST (in my case, using Postman) the JSON snippet below which was attempted in the two seperate manners outlined below.
```json
{
    "name": "Test Business 1",
    "phone": "555-555-5555",
    "hours": "TEST HOURS",
    "coordinates_latitude": 1.2345,
    "coordinates_longitude": 6.7890,
    "prices_oneHundred": 1.00,
    "prices_oneFifty": 1.50,
    "prices_twoHundred": 2.00
}
```

```json
{
    "name": "Test Business 1",
    "phone": "555-555-5555",
    "hours": "TEST HOURS",
    "latitude": 1.2345,
    "longitude": 6.7890,
    "oneHundred": 1.00,
    "oneFifty": 1.50,
    "twoHundred": 2.00
}
```

### Expected behavior

The expectation is that one should be able to POST using @Group without fatal erroring.

### Environment

* Vapor Framework version: 4.65.0
* Vapor Toolbox version: 18.5.1
* FluentKit Version: 1.35.0
* OS version: 12.5 (21G72)

**Comment by gwynne** [comment]
This is a very confusing behavior by `@Group`, but is not a bug. The correct JSON-encoded form of your model would be:

```json
{
    "name": "Test Business 1",
    "phone": "555-555-5555",
    "hours": "TEST HOURS",
    "coordinates": {
        "latitude": 1.2345,
        "longitude": 6.7890
    },
    "prices": {
        "oneHundred": 1.00,
        "oneFifty": 1.50,
        "twoHundred": 2.00
    }
}
```

**Comment by haIIux** [comment]
Thank you for correcting the JSON data, that makes more sense and I'm honestly not sure why I didn't think to try that.

**Comment by 0xTim** [comment]
We should definitely remove the fatal error. We shouldn't allow any request data to cause a crash, that's a potential security vulnerability

**Comment by jdmcd** [comment]
Agreed ^, that's what I came here to say

**Comment by haIIux** [comment]
While I am glad I found this bug so to speak, I wish I could be of more help. Please let me know if there's anything someone whom is fresh in Vapor could do to help you @gwynne.

**Comment by gwynne** [comment]
It's worth noting here that the design flaws of the Fluent property wrappers as a whole make it much more advisable to use a DTO on the Codable side of things; Tanner's ideal of models being directly transferrable from requests to database and vice versa did not pan out in the current design.
