### ISSUE TITLE
Generated queries have non-deterministic ordering of columns, which trash monitoring/logging/performance

### ISSUE THREAD

**Issue by Remi-C** [vapor/fluent-kit#543]
**Is your feature request related to a problem? Please describe.**
We use this ORM to generate inserts in a postgres db.
Looking at the DB logs, the inserts have random order of columns.
The insert end up inserting the same dat, but is very bad for performance (makes it harder for the DB to cache plans),
and terrible for monitoring/analytics (the same query appears as dozens of different queries depending the order of columns)

here is an example of 10 different inserts actually doing the same thing
``` SQL
INSERT INTO my_table ("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8", "col9", "col10", "col11", "col12", "col13", "col14", "col15", "col16", "col17", "col18", "col19", "col20", "col21", "col22", "col23") VALUES ($1, $2, NULL, $3, $4, $5, $6, NULL, $7, DEFAULT, $8, $9, $10, $11, $12, $13, $14, NULL, $15, $16, $17, $18, $19) RETURNING "col10"
INSERT INTO my_table ("col9", "col7", "col16", "col19", "col2", "col18", "col15", "col13", "col3", "col5", "col1", "col10", "col22", "col6", "col8", "col21", "col12", "col23", "col11", "col20", "col4", "col14", "col17") VALUES ($1, $2, $3, $4, $5, NULL, $6, $7, NULL, $8, $9, DEFAULT, $10, $11, NULL, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "col10"
INSERT INTO my_table ("col21", "col2", "col18", "col10", "col12", "col20", "col9", "col8", "col15", "col6", "col5", "col11", "col13", "col22", "col7", "col16", "col14", "col3", "col4", "col23", "col17", "col19", "col1") VALUES ($1, $2, NULL, DEFAULT, $3, $4, $5, NULL, $6, $7, $8, $9, $10, $11, $12, $13, $14, NULL, $15, $16, $17, $18, $19) RETURNING "col10"
INSERT INTO my_table ("col7", "col16", "col23", "col1", "col10", "col21", "col20", "col8", "col17", "col12", "col14", "col11", "col2", "col4", "col18", "col9", "col22", "col13", "col15", "col5", "col6", "col3", "col19") VALUES ($1, $2, $3, $4, DEFAULT, $5, $6, NULL, $7, $8, $9, $10, $11, $12, NULL, $13, $14, $15, $16, $17, $18, NULL, $19) RETURNING "col10"
INSERT INTO my_table ("col19", "col6", "col20", "col13", "col11", "col4", "col10", "col15", "col18", "col1", "col5", "col23", "col16", "col8", "col7", "col14", "col22", "col2", "col12", "col21", "col9", "col3", "col17") VALUES ($1, $2, $3, $4, $5, $6, DEFAULT, $7, NULL, $8, $9, $10, $11, NULL, $12, $13, $14, $15, $16, $17, $18, NULL, $19) RETURNING "col10"
INSERT INTO my_table ("col15", "col21", "col17", "col20", "col5", "col9", "col12", "col2", "col16", "col13", "col11", "col4", "col23", "col1", "col18", "col3", "col8", "col7", "col10", "col19", "col14", "col6", "col22") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NULL, NULL, NULL, $15, DEFAULT, $16, $17, $18, $19) RETURNING "col10"
INSERT INTO my_table ("col17", "col11", "col9", "col21", "col18", "col16", "col10", "col13", "col4", "col3", "col12", "col23", "col7", "col1", "col19", "col14", "col5", "col15", "col6", "col22", "col20", "col8", "col2") VALUES ($1, $2, $3, $4, NULL, $5, DEFAULT, $6, $7, NULL, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, NULL, $19) RETURNING "col10"
INSERT INTO my_table ("col21", "col16", "col1", "col17", "col6", "col13", "col19", "col8", "col5", "col2", "col11", "col7", "col18", "col9", "col15", "col10", "col14", "col20", "col22", "col3", "col12", "col4", "col23") VALUES ($1, $2, $3, $4, $5, $6, $7, NULL, $8, $9, $10, $11, NULL, $12, $13, DEFAULT, $14, $15, $16, NULL, $17, $18, $19) RETURNING "col10"
INSERT INTO my_table ("col1", "col10", "col2", "col9", "col5", "col17", "col23", "col6", "col11", "col16", "col12", "col7", "col13", "col21", "col3", "col18", "col15", "col22", "col4", "col14", "col19", "col8", "col20") VALUES ($1, DEFAULT, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NULL, NULL, $14, $15, $16, $17, $18, NULL, $19) RETURNING "col10"
INSERT INTO my_table ("col23", "col5", "col16", "col17", "col11", "col2", "col21", "col4", "col7", "col18", "col14", "col12", "col19", "col15", "col20", "col6", "col13", "col22", "col8", "col10", "col1", "col3", "col9") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NULL, $10, $11, $12, $13, $14, $15, $16, $17, NULL, DEFAULT, $18, NULL, $19) RETURNING "col10"
```

**Describe the solution you'd like**
The order of columns in any statement should be deterministic ! 
It does not really matter what the order is (alphabetical, following order of declaration in class, etc.),
as long as it's consistent.

**Describe alternatives you've considered**
Maybe provide a parameter to allow generated statements to be deterministic, although I have trouble seeing in which situation the current behavior is preferable.

**Additional context**
Non-deterministic behavior like that make any logging/ debugging/monitoring much harder.

**Comment by rausnitz** [comment]
If the package maintainers are receptive, I think adding `.sorted { $0.description < $1.description }` to the line https://github.com/vapor/fluent-kit/blob/main/Sources/FluentSQL/SQLQueryConverter.swift#L83 would be the only necessary change. I'd be happy to make a PR if so.

I'm curious how the test assertion https://github.com/vapor/fluent-kit/blob/main/Tests/FluentKitTests/FluentKitTests.swift#L706 is able to succeed consistently, considering the column order is not deterministic. 🤔 (It's failing locally for me.)

**Comment by 0xTim** [comment]
@gwynne happy to add the above sorting? I think making it better for monitoring and logging is a decent use case and it shouldn't really hit performance. We could always add it behind a flag if we're worried about it.

@rausnitz [in CI we set](https://github.com/vapor/ci/blob/reusable-workflows/.github/workflows/run-unit-tests.yml#L91) the `SWIFT_DETERMINISTIC_HASHING` flag which forces the hashing algorithm to produce consistent results. Great for tests but you don't want this in the real world

**Comment by gwynne** [comment]
Typically, in a case such as this, I would advise users to drop down to SQLKit to construct their queries. Helpers exist in FluentKit's `FluentSQL` module which enable handling of Fluent models in SQLKit queries. In the near future, there will be a release of a considerably expanded API for SQLKit (or more precisely, an intermediary API that is conceptually more or less in-between FluentKit and SQLKit) which enables building SQLKit queries in a fashion largely similar to working with Fluent's API, combining the convenience of the higher-level API's syntax with the much greater control provided by the lower-level API. For example, in the current public SQLKit API, one of the `INSERT` queries above might be constructed something like this:

```swift

let returnedCol10Values = try await sqlDatabase.insert(into: MyTable.schema)
    .model(myModel) // ... except this helper does not actually work with Fluent models as written, because it
                                   // operates via Codable rather than Fluent's database property protocols. Instead, the various
                                   // pieces must be specified manually:
    .columns(SQLIdentifier(MyTable.path(for: \.$col1).first!.description), /* repeat for each column */)
    .values([
        SQLBind(myModel.col1), SQLBind(myModel.col2), SQLLiteral.null ,SQLBind(myModel.col4),
        // ... and so on ...
    ])
    // if the model has `@Timestamp` properties that would otherwise be automatically managed by Fluent,
    // they must be explicitly specified in the column list and included in the value list with either
    // `SQLBind(Date())` (slow and wasteful) or `SQLFunction("now")`
    // if the model has `@Timestamp` properties that would otherwise be automatically managed by Fluent,
    // they must be explicitly set on the model in order to be saved by an insert such as this
    .returning(MyTable.path(for: \.$col10).first!.description)
    .all(decoding: /* the type of MyTable.col10 */.self)
```

Using one of the prototype API designs for the new APIs, it would look more like this:
```swift
let returnedCol10Values = try await sqlDatabase.insert(into: MyTable.self)
    .modelValue(myModel) // this version of the helper is aware of Fluent models
    .all(decoding: \MyTable.$col10)
// The above very concise query unfortunately still incurs the full performance penalty involved in Fluent's
// use of Mirror for reflection, negating one of SQLKit's major advantages. But if one is willing to write things
// out a bit more explicitly, that overhead can be completely bypassed while still leveraging the definitions
// and type information on the Fluent model definition:
let returnedCol10Values = try await sqlDatabase.insert(into: MyTable.self)
    .columns(MyTable.self, \.$col1, \.$col2, \.$col3, \.$col4, /* et al */)
    // Note: I've made up a few various input values to show the usage of various helpers
    .values(.bind(myModel.col1), .bind(myModel.col2), .nullValue(), .now(), .number(5), .bool(true), /* and so on */)
    .all(decoding: \MyTable.$col10)
```

This only shows a very small subsection of the improved API, but the point I'm driving at is that while at current, SQLKit queries must usually be enormously verbose and unwieldy in order to avoid incurring FluentKit's overhead, this will soon no longer be the case. (And, I should add since I didn't mention it anywhere above yet, the resulting generated SQL is entirely deterministic as long as the inputs are, unlike queries generated by FluentKit.) Given that you cite performance as one of the concerns involved, the extreme performance improvements available simply by avoiding Fluent's querying APIs would presumably be a more attractive solution than slowing Fluent itself down even further (if only very slightly so).

**Comment by rausnitz** [comment]
Another thought I had would be to replace the dictionary on this line https://github.com/vapor/fluent-kit/blob/main/Sources/FluentSQL/SQLQueryConverter.swift#L80 with an array, where each element is a tuple or some other data structure containing a column and a value-to-be-inserted.

I don't see what benefit the dictionary brings. In `SQLQueryConverter.insert(_:)` for example, the function gets the dictionary, makes an array of the dictionary's keys, and then looks up the dictionary value associated with each key. Seems like it would be more straightforward to start with an array of columns+values, then iterate over it.

**Comment by gwynne** [comment]
@rausnitz It's funny you should mention that particular code - earlier today I streamlined that very method as part of a feature PR I'm nearly done with. Great minds think alike!

**Comment by gwynne** [comment]
The honest truth of the matter is that the runtime overhead of `Mirror` is an order of magnitude or so greater than that of any other performance bottleneck in Fluent, as of the last time I profiled it a few months ago. The next worst bottleneck is `Codable` (especially for models containing columns which, when using an SQL database driver, are saved as JSON; usually structures and arrays), a far distant second. Even the support for property wrapper requirements in protocols that I'm working on wouldn't fully eliminate the Mirror overhead; it would only cut the average number of invocations by roughly half. SE-0385 would probably go most or all of the rest of the way, but a clean, performance-focused API design will still have to wait for Fluent 5.
