### ISSUE TITLE
owner likely unsaved, attach within attach closure

### ISSUE THREAD

**Issue by wibed** [vapor/fluent-kit#586]
related to recent pr:
https://github.com/vapor/fluent-kit/pull/585

mentionable:
- database is a transaction here

code:
```swift
    try await event.$account.attach(Account, on: database, { roster in
      try await roster.$promise.attach(Promise, on: database) })
```

```swift
[Vapor] siblings relation Siblings<Roster, Promise, RosterPromise>
(from: [roster_id], to: [promise_id]) is missing owning model's ID (owner likely unsaved)
```

**Comment by gwynne** [comment]
Right - the roster model hasn't been saved yet while you're still editing it, so you can't use the attach methods on it unless you manually allocate an ID for it and assign that ID to the model before returning from the closure.

**Comment by wibed** [comment]
thanks for the clarification!
