### ISSUE TITLE
Migrations should not mention model

### ISSUE THREAD

**Issue by ScottRobbins** [vapor/fluent-kit#59]
In the api template currently: https://github.com/vapor/api-template/blob/4/Sources/App/Migrations/CreateTodo.swift

It starts with the line `Todo.schema(on: database)`

I think that migrations should probably be completely separate from the fluent models. By referencing the fluent model here, it means if you ever rename the table, you'd probably want to rename the model. But doing that would mean that previous migrations that referenced the model would have to change, which is kind of weird doesn't accurately reflect how things were migrated throughout time.

**Comment by tanner0101** [comment]
Agreed, this is how things work in latest Fluent 4 👍
