### ISSUE TITLE
Separate Field property wrappers into separate package

### ISSUE THREAD

**Issue by lmcd** [vapor/fluent-kit#597]
I have a model In my project that is simply serialised and sent to a Swift server to process.
My client-side build needs a whole bunch of `nio` dependancies simply to accommodate some properties decorated with a `@Field` annotation.

Is it possible to separate this so I can use `@Field`, `@ID` etc without needing `swift-nio`?

**Comment by 0xTim** [comment]
@lmcd No I don't think it is. The property wrappers require the enclosing type to be a `Model` to make all the syntactic sugar work and there's not really a way around that. 

For sharing models across server and clients, we strongly recommend sharing only DTOs which doesn't have this issue

**Comment by 0xTim** [comment]
Will close this out, feel free to reopen if you have any other suggestions
