### ISSUE TITLE
Swift 6 `IS NOT NULL` where clause regression

### ISSUE THREAD

**Issue by finestructure** [vapor/fluent-kit#612]
One of our [unit tests](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/swift-6-prep/Tests/AppTests/API%2BPackageControllerTests.swift#L282) is failing when running it with Swift 6. The underlying cause seems to be a regression in how the `WHERE` clause is being rendered.

In Swift 5.10 we get

```sql
WHERE "versions"."latest" IS NOT NULL
```

(notably without any bind parameter).

In Swift 6 this ends up as

```sql
WHERE "versions"."latest" <> $1
```

with a bind parameter `nil` and this does not actually select results like the 5.10 query doesn't.

**Comment by 0xTim** [comment]
Looks like a duplicate of #611

**Comment by 0xTim** [comment]
@finestructure can you confirm this is fixed in the latest Xcode beta?

**Comment by finestructure** [comment]
Yes, these tests are now passing, thank you!

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/9910852316
