### ISSUE TITLE
optional relations

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent-kit#62]
`@Parent`, `@Children`, and `@Siblings` should support optional relations. 

Some ways to achieve this are:
1: Make all relations optional
2: Make all relations optional and provide `@Required*` versions, i.e., `@RequiredParent`
3: Make all relations required and provide `@Optional*` versions, i.e., `@OptionalParent`
4: Allow relations to be declared as optional / required on individual basis, i.e.:

> Note: It's unclear whether this one would be easy to do with property wrappers, but it has a very nice API

```swift
// optional relation
@Parent(...)
var galaxy: Galaxy?

// required relation
@Parent(...)
var galaxy: Galaxy
```

**Comment by adtrevor** [comment]
If we can't go with solution number four, I agree with @mcdappdev: it would be better to avoid `@Required*` as I feel it would make the syntax "heavier" for what is probably going to be the most commonly used type of relation.

@tanner0101 When you say it's not clear wether or not 4) is makable, what are the main issues you are seeing? From what I just tried it's not possible to overload the property warper init so it seems like a dynamic cast is required, is this about performance you are worried?

**Comment by tanner0101** [comment]
`@OptionalParent` was added a while back. Closing this.
