### ISSUE TITLE
Improving optional fields

### ISSUE THREAD

**Issue by adtrevor** [vapor/fluent-kit#66]
On database schema creation, there is the `.required` option that lets you specify a certain field shouldn't be optional, this leads me to two questions / ideas for improvements:
- Why not making fields required by default and adding an opt-in `.optional` parameter? Wouldn't this be more in-line with Swift where values can never be "`null`"/`nil` except if they are optionals?
- Instead of using `.required` or `.optional`, couldn't we just add a new type of field, such as `.optional(FieldType)` that would let users create their fields with `.optional(.int)` for instance? This way they wouldn't have anymore to specify separately if the field is required or not.

This is a breaking change obviously so it would be nice think about this before the 4.0 release.

Tell me what you think! 🙂

**Comment by tanner0101** [comment]
The `SchemaBuilder` syntax is meant to be more similar to what exists in the database than Swift's type system. In the database, each field has a type and that field can have additional constraints, such as requiring the value to not be null. Eventually I'd like Fluent to have automatic migrations based on type system information but that's a much larger feature and better reflection in Swift would probably be needed.
