### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent-kit#67]
The `Database` type should support running queries in a transaction, so queries can be run and then rolled-back if an error occurs. The syntax should probably look something like this:

```swift
database.transaction {
    return users.save(on: database).flatMap {
        return properties.save(on: database)
    }
}
```

In this case, if saving the `Property` models fails, then the transaction gets rolled back and the `User` models aren't saved either. If all the inserts succeed, then the transaction is committed and the data stays in the database.

One feature that would be nice would be to include isolation levels for the transaction. This is a feature in MySQL and Postgres that allows you to define how the data in the transaction can be accessed between different threads, such as whether the data that has been inserted can be read before the transaction is committed or not. For this, you would pass in a flag to the `transaction` method:

```swift
database.transaction(.uncommited) {
    // Run queries now...
}
```

**Comment by Jerry-Carter** [comment]
Adding transaction support to the beta should be a priority.  ACID functionality is, of course, a key feature of relational databases and essential for many applications.  Getting this out for testing and feedback prior to release would seem to be very important.

**Comment by Jerry-Carter** [comment]
I like the simplicity of Caleb's proposal.  From a user interface standpoint, this should be enough.  I have a minor fear that the isolation levels may differ slightly between databases -- but I feel strongly that the isolation level should be controllable by the application author.

**Comment by tanner0101** [comment]
Fluent 3 style transaction APIs were added in #159

**Comment by ptrkstr** [comment]
FYI transaction isolation conversation now has its own issue [here](https://github.com/vapor/fluent-kit/issues/167)
