### ISSUE TITLE
QueryBuilder creates invalid SQL when uniqueIDs is empty

### ISSUE THREAD

**Issue by cpageler93** [vapor/fluent-kit#73]
Hi,

I have the following model structure:

- **User** can be in multiple teams
- **TeamUser** connects users with teams, isActive controls the active team
- **Team** can contain multiple (active and inactive) users

```swift
final class User: Model, Content {

    // ... other attributes 

    @Children(from: \.$user)
    var teamUsers: [TeamUser]

    @Siblings(through: TeamUser.self, from: \.$user, to: \.$team)
    var teams: [Team]

}
```

```swift
final class TeamUser: Model, Content {

    // ... other attributes 

    @Parent(key: "userId")
    var user: User

    @Parent(key: "teamId")
    var team: Team

    @Field(key: "isActive")
    var isActive: Bool

}
```

```swift
final class Team: Model, Content {

    // ... other attributes 

    @Children(from: \.$team)
    var teamUsers: [TeamUser]

    @Siblings(through: TeamUser.self, from: \.$team, to: \.$user)
    var users: [User]

}
```

## Where my problem starts

I'd like to query the active team with the following method, which works when the user is in at least one team.

```swift
public func activeTeam(on db: Database) throws -> EventLoopFuture<Team?> {
    return try $teamUsers
        .query(on: db)
        .with(\.$team)
        .filter(\.$isActive == true)
        .first()
        .map { $0?.team }
}
```

When the user is not connected to any `Team` (or `TeamUser`) I get the following error:

```
[ ERROR ] MySQL error: Server error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
```

I figured out that the SQL command which produces this error is the following:

```mysql
SELECT `teams`.`id`, `teams`.`name`, `teams`.`imageURL`, `teams`.`isPublic`, `teams`.`createdAt`
FROM `teams`
WHERE `teams`.`id` IN ()
```

which is built here:

https://github.com/vapor/fluent-kit/blob/738672beb2a743df8b7566094c5a268bee2345a8/Sources/FluentKit/Properties/Parent.swift#L142-L151

I'm not sure if this is an implementation error on my side or in Fluent Kit. I'd assume that it's not  even necessary to perform a query in line 147 after we figured out that `uniqueIDs` is empty in line 146. But is that the correct place in code to fix the problem?

**Comment by tanner0101** [comment]
This issue has been fixed in the latest version. Run `swift package update` and try the query again, thanks!
