### ISSUE TITLE
One-to-one relations

### ISSUE THREAD

**Issue by fwgreen** [vapor/fluent-kit#74]
A single `@Child` relation would allow for one-to-one relationships with an owning side, similar to JPA's `@OneToOne` relationship when using the `mappedBy` element on the dependent side.  Single `@Sibling` would allow for one-to-one relationships without a join table.

**Comment by kaishin** [comment]
Agreed that this would be a nice addition. @tanner0101 Thoughts on the idea?

**Comment by tanner0101** [comment]
+1 to supporting this. It's not high priority though since `@Children`, `@Siblings`, and some unique constraints can be used to achieve this already.

**Comment by gwynne** [comment]
Implemented in #419
