### ISSUE TITLE
DatabaseOutput.decode<T> prototype allow for a Decoder to be injected

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/fluent-kit#86]
The `DatabaseOutput` protocol should allow for a `Decoder` to be injected.

Expected behaviour:

`func decode<D, Decoder>(column: String, as type: D.Type, using decoder: Decoder) throws -> D where D : Decodable`

Current behaviour (example from MySQLKit):
```
extension MySQLRow: SQLRow {
    public func decode<D>(column: String, as type: D.Type) throws -> D where D : Decodable {
        guard let data = self.column(column) else {
            fatalError()
        }
        return try MySQLDataDecoder().decode(D.self, from: data)
    }
}
```

`MySQLDataDecoder()` is created every time inside the decoding function. This prevents the use of more complex decoding strategies, available on `JSONDecoder` or in my specific case in `BSONDecoder`.

**Comment by tanner0101** [comment]
This can be passed into the row's init method.
