### ISSUE TITLE
Allow custom property wrappers for relationships

### ISSUE THREAD

**Issue by samalone** [vapor/fluent-kit#92]
The Fluent APIs should allow users to define their own property wrappers (similar to `@Parent` and `@Children`) to create custom mappings between the user's model objects and database records. As of Fluent 4.0.0-beta.1, several important protocols and fields have internal access, so it's not possible for users to define their own property wrappers. These include:

- AnyField
- AnyProperty
- _ModelCodingKey
- Field._$id

Make these public, cleaning up the APIs if necessary, so that users can create their own property wrappers.

I hope to make these changes for my own use and issue a pull request back to the main project. All suggestions and feedback are much appreciated.

## Background

In my case, I am creating a data model where nearly all model objects are versioned in the database. That means that each reference to another model object requires two joins: one to determine the current version of the related record, and another to retrieve the related record. Retrieving the version history of a model object is possible, but is a much rarer operation. In most cases the data model simply wants to treat the versioned object as a simple relationship and hide the complexity of the double join from the user of the data model.

I would like to create my own `@VersionedParent` and `@VersionedChildren` property wrappers that handle these relationships automatically.

**Comment by tanner0101** [comment]
All of these protocols have since been publicized. You should be able to define your own property wrapper types now. If there are any other things you need still internal, let me know. Thanks!
