### ISSUE TITLE
Check Whether a Field is Initialized

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent-kit#99]
Instead of storing field values as optionals, there should be a custom enum used, something like `FieldValue<T>` that has two cases, `initialized(T)` and `uninitialized`. Then a property flag should be added to all the field types, `initialized:L Bool`. This would allow an application to check and see if a field has been initialized with a value or not.

**Comment by tanner0101** [comment]
This is possible with the new optional `value` property on all fields and relations.
